// Package kong provides a client for the "kongswap" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package kong

import (
	"github.com/aviate-labs/agent-go"
	"github.com/aviate-labs/agent-go/candid/idl"
	"github.com/aviate-labs/agent-go/principal"
	"github.com/niccolofant/ic-arb/core/icp"
)

type Icrc10SupportedStandards struct {
	Url  string `ic:"url" json:"url"`
	Name string `ic:"name" json:"name"`
}

type Icrc21ConsentMessageMetadata struct {
	Language         string `ic:"language" json:"language"`
	UtcOffsetMinutes *int16 `ic:"utc_offset_minutes,omitempty" json:"utc_offset_minutes,omitempty"`
}

type Icrc21ConsentMessageSpec struct {
	Metadata   Icrc21ConsentMessageMetadata `ic:"metadata" json:"metadata"`
	DeviceSpec *struct {
		GenericDisplay *idl.Null `ic:"GenericDisplay,variant" json:"GenericDisplay,omitempty"`
		LineDisplay    *struct {
			CharactersPerLine uint16 `ic:"characters_per_line" json:"characters_per_line"`
			LinesPerPage      uint16 `ic:"lines_per_page" json:"lines_per_page"`
		} `ic:"LineDisplay,variant" json:"LineDisplay,omitempty"`
	} `ic:"device_spec,omitempty" json:"device_spec,omitempty"`
}

type Icrc21ConsentMessageRequest struct {
	Method          string                   `ic:"method" json:"method"`
	Arg             []byte                   `ic:"arg" json:"arg"`
	UserPreferences Icrc21ConsentMessageSpec `ic:"user_preferences" json:"user_preferences"`
}

type Icrc21ConsentMessage struct {
	GenericDisplayMessage *string `ic:"GenericDisplayMessage,variant" json:"GenericDisplayMessage,omitempty"`
	LineDisplayMessage    *struct {
		Pages []struct {
			Lines []string `ic:"lines" json:"lines"`
		} `ic:"pages" json:"pages"`
	} `ic:"LineDisplayMessage,variant" json:"LineDisplayMessage,omitempty"`
}

type Icrc21ErrorInfo struct {
	Description string `ic:"description" json:"description"`
}

type Icrc21Error struct {
	UnsupportedCanisterCall   *Icrc21ErrorInfo `ic:"UnsupportedCanisterCall,variant" json:"UnsupportedCanisterCall,omitempty"`
	ConsentMessageUnavailable *Icrc21ErrorInfo `ic:"ConsentMessageUnavailable,variant" json:"ConsentMessageUnavailable,omitempty"`
	InsufficientPayment       *Icrc21ErrorInfo `ic:"InsufficientPayment,variant" json:"InsufficientPayment,omitempty"`
	GenericError              *struct {
		ErrorCode   idl.Nat `ic:"error_code" json:"error_code"`
		Description string  `ic:"description" json:"description"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
}

type Icrc28TrustedOriginsResponse struct {
	TrustedOrigins []string `ic:"trusted_origins" json:"trusted_origins"`
}

type TxId struct {
	BlockIndex    *idl.Nat `ic:"BlockIndex,variant" json:"BlockIndex,omitempty"`
	TransactionId *string  `ic:"TransactionId,variant" json:"TransactionId,omitempty"`
}

type ICTransferReply struct {
	Chain      string  `ic:"chain" json:"chain"`
	Symbol     string  `ic:"symbol" json:"symbol"`
	IsSend     bool    `ic:"is_send" json:"is_send"`
	Amount     idl.Nat `ic:"amount" json:"amount"`
	CanisterId string  `ic:"canister_id" json:"canister_id"`
	BlockIndex idl.Nat `ic:"block_index" json:"block_index"`
}

type TransferReply struct {
	IC *ICTransferReply `ic:"IC,variant" json:"IC,omitempty"`
}

type TransferIdReply struct {
	TransferId uint64        `ic:"transfer_id" json:"transfer_id"`
	Transfer   TransferReply `ic:"transfer" json:"transfer"`
}

type UserReply struct {
	UserId              uint32  `ic:"user_id" json:"user_id"`
	PrincipalId         string  `ic:"principal_id" json:"principal_id"`
	AccountId           string  `ic:"account_id" json:"account_id"`
	MyReferralCode      string  `ic:"my_referral_code" json:"my_referral_code"`
	ReferredBy          *string `ic:"referred_by,omitempty" json:"referred_by,omitempty"`
	ReferredByExpiresAt *uint64 `ic:"referred_by_expires_at,omitempty" json:"referred_by_expires_at,omitempty"`
	FeeLevel            uint8   `ic:"fee_level" json:"fee_level"`
	FeeLevelExpiresAt   *uint64 `ic:"fee_level_expires_at,omitempty" json:"fee_level_expires_at,omitempty"`
}

type UserResult struct {
	Ok  *UserReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string    `ic:"Err,variant" json:"Err,omitempty"`
}

type UserBalancesReply struct {
	LP *LPBalancesReply `ic:"LP,variant" json:"LP,omitempty"`
}

type LPBalancesReply struct {
	Name       string  `ic:"name" json:"name"`
	Symbol     string  `ic:"symbol" json:"symbol"`
	LpTokenId  uint64  `ic:"lp_token_id" json:"lp_token_id"`
	Balance    float64 `ic:"balance" json:"balance"`
	UsdBalance float64 `ic:"usd_balance" json:"usd_balance"`
	Chain0     string  `ic:"chain_0" json:"chain_0"`
	Symbol0    string  `ic:"symbol_0" json:"symbol_0"`
	Address0   string  `ic:"address_0" json:"address_0"`
	Amount0    float64 `ic:"amount_0" json:"amount_0"`
	UsdAmount0 float64 `ic:"usd_amount_0" json:"usd_amount_0"`
	Chain1     string  `ic:"chain_1" json:"chain_1"`
	Symbol1    string  `ic:"symbol_1" json:"symbol_1"`
	Address1   string  `ic:"address_1" json:"address_1"`
	Amount1    float64 `ic:"amount_1" json:"amount_1"`
	UsdAmount1 float64 `ic:"usd_amount_1" json:"usd_amount_1"`
	Ts         uint64  `ic:"ts" json:"ts"`
}

type UserBalancesResult struct {
	Ok  *[]UserBalancesReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string              `ic:"Err,variant" json:"Err,omitempty"`
}

type MessagesReply struct {
	MessageId uint64 `ic:"message_id" json:"message_id"`
	Title     string `ic:"title" json:"title"`
	Message   string `ic:"message" json:"message"`
	Ts        uint64 `ic:"ts" json:"ts"`
}

type MessagesResult struct {
	Ok  *[]MessagesReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string          `ic:"Err,variant" json:"Err,omitempty"`
}

type TokenReply struct {
	LP *LPTokenReply `ic:"LP,variant" json:"LP,omitempty"`
	IC *ICTokenReply `ic:"IC,variant" json:"IC,omitempty"`
}

type LPTokenReply struct {
	TokenId     uint32  `ic:"token_id" json:"token_id"`
	Chain       string  `ic:"chain" json:"chain"`
	Address     string  `ic:"address" json:"address"`
	Name        string  `ic:"name" json:"name"`
	Symbol      string  `ic:"symbol" json:"symbol"`
	PoolIdOf    uint32  `ic:"pool_id_of" json:"pool_id_of"`
	Decimals    uint8   `ic:"decimals" json:"decimals"`
	Fee         idl.Nat `ic:"fee" json:"fee"`
	TotalSupply idl.Nat `ic:"total_supply" json:"total_supply"`
	IsRemoved   bool    `ic:"is_removed" json:"is_removed"`
}

type ICTokenReply struct {
	TokenId    uint32  `ic:"token_id" json:"token_id"`
	Chain      string  `ic:"chain" json:"chain"`
	CanisterId string  `ic:"canister_id" json:"canister_id"`
	Name       string  `ic:"name" json:"name"`
	Symbol     string  `ic:"symbol" json:"symbol"`
	Decimals   uint8   `ic:"decimals" json:"decimals"`
	Fee        idl.Nat `ic:"fee" json:"fee"`
	Icrc1      bool    `ic:"icrc1" json:"icrc1"`
	Icrc2      bool    `ic:"icrc2" json:"icrc2"`
	Icrc3      bool    `ic:"icrc3" json:"icrc3"`
	IsRemoved  bool    `ic:"is_removed" json:"is_removed"`
}

type TokensResult struct {
	Ok  *[]TokenReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string       `ic:"Err,variant" json:"Err,omitempty"`
}

type PoolReply struct {
	PoolId        uint32  `ic:"pool_id" json:"pool_id"`
	Name          string  `ic:"name" json:"name"`
	Symbol        string  `ic:"symbol" json:"symbol"`
	Chain0        string  `ic:"chain_0" json:"chain_0"`
	Symbol0       string  `ic:"symbol_0" json:"symbol_0"`
	Address0      string  `ic:"address_0" json:"address_0"`
	Balance0      idl.Nat `ic:"balance_0" json:"balance_0"`
	LpFee0        idl.Nat `ic:"lp_fee_0" json:"lp_fee_0"`
	Chain1        string  `ic:"chain_1" json:"chain_1"`
	Symbol1       string  `ic:"symbol_1" json:"symbol_1"`
	Address1      string  `ic:"address_1" json:"address_1"`
	Balance1      idl.Nat `ic:"balance_1" json:"balance_1"`
	LpFee1        idl.Nat `ic:"lp_fee_1" json:"lp_fee_1"`
	Price         float64 `ic:"price" json:"price"`
	LpFeeBps      uint8   `ic:"lp_fee_bps" json:"lp_fee_bps"`
	LpTokenSymbol string  `ic:"lp_token_symbol" json:"lp_token_symbol"`
	IsRemoved     bool    `ic:"is_removed" json:"is_removed"`
}

type PoolsResult struct {
	Ok  *[]PoolReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string      `ic:"Err,variant" json:"Err,omitempty"`
}

type PoolExpectedBalance struct {
	PoolSymbol string  `ic:"pool_symbol" json:"pool_symbol"`
	Balance    idl.Nat `ic:"balance" json:"balance"`
	LpFee      idl.Nat `ic:"lp_fee" json:"lp_fee"`
	KongFee    idl.Nat `ic:"kong_fee" json:"kong_fee"`
}

type ExpectedBalance struct {
	Balance         idl.Nat               `ic:"balance" json:"balance"`
	PoolBalances    []PoolExpectedBalance `ic:"pool_balances" json:"pool_balances"`
	UnclaimedClaims idl.Nat               `ic:"unclaimed_claims" json:"unclaimed_claims"`
}

type CheckPoolsReply struct {
	Symbol          string          `ic:"symbol" json:"symbol"`
	ActualBalance   idl.Nat         `ic:"actual_balance" json:"actual_balance"`
	ExpectedBalance ExpectedBalance `ic:"expected_balance" json:"expected_balance"`
	DiffBalance     idl.Int         `ic:"diff_balance" json:"diff_balance"`
}

type CheckPoolsResult struct {
	Ok  *[]CheckPoolsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string            `ic:"Err,variant" json:"Err,omitempty"`
}

type TxsReply struct {
	AddPool         *AddPoolReply         `ic:"AddPool,variant" json:"AddPool,omitempty"`
	AddLiquidity    *AddLiquidityReply    `ic:"AddLiquidity,variant" json:"AddLiquidity,omitempty"`
	RemoveLiquidity *RemoveLiquidityReply `ic:"RemoveLiquidity,variant" json:"RemoveLiquidity,omitempty"`
	Swap            *SwapReply            `ic:"Swap,variant" json:"Swap,omitempty"`
}

type TxsResult struct {
	Ok  *[]TxsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string     `ic:"Err,variant" json:"Err,omitempty"`
}

type RequestRequest struct {
	AddPool         *AddPoolArgs         `ic:"AddPool,variant" json:"AddPool,omitempty"`
	AddLiquidity    *AddLiquidityArgs    `ic:"AddLiquidity,variant" json:"AddLiquidity,omitempty"`
	RemoveLiquidity *RemoveLiquidityArgs `ic:"RemoveLiquidity,variant" json:"RemoveLiquidity,omitempty"`
	Swap            *SwapArgs            `ic:"Swap,variant" json:"Swap,omitempty"`
}

type RequestReply struct {
	Pending         *idl.Null             `ic:"Pending,variant" json:"Pending,omitempty"`
	AddPool         *AddPoolReply         `ic:"AddPool,variant" json:"AddPool,omitempty"`
	AddLiquidity    *AddLiquidityReply    `ic:"AddLiquidity,variant" json:"AddLiquidity,omitempty"`
	RemoveLiquidity *RemoveLiquidityReply `ic:"RemoveLiquidity,variant" json:"RemoveLiquidity,omitempty"`
	Swap            *SwapReply            `ic:"Swap,variant" json:"Swap,omitempty"`
}

type RequestsReply struct {
	RequestId uint64         `ic:"request_id" json:"request_id"`
	Statuses  []string       `ic:"statuses" json:"statuses"`
	Request   RequestRequest `ic:"request" json:"request"`
	Reply     RequestReply   `ic:"reply" json:"reply"`
	Ts        uint64         `ic:"ts" json:"ts"`
}

type RequestsResult struct {
	Ok  *[]RequestsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string          `ic:"Err,variant" json:"Err,omitempty"`
}

type TransfersResult struct {
	Ok  *[]TransferIdReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string            `ic:"Err,variant" json:"Err,omitempty"`
}

type AddTokenArgs struct {
	Token string `ic:"token" json:"token"`
}

type AddTokenReply struct {
	IC *ICTokenReply `ic:"IC,variant" json:"IC,omitempty"`
}

type AddTokenResult struct {
	Ok  *AddTokenReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string        `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateTokenArgs struct {
	Token string `ic:"token" json:"token"`
}

type UpdateTokenReply struct {
	IC *ICTokenReply `ic:"IC,variant" json:"IC,omitempty"`
}

type UpdateTokenResult struct {
	Ok  *UpdateTokenReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string           `ic:"Err,variant" json:"Err,omitempty"`
}

type AddPoolArgs struct {
	Token0   string  `ic:"token_0" json:"token_0"`
	Amount0  idl.Nat `ic:"amount_0" json:"amount_0"`
	TxId0    *TxId   `ic:"tx_id_0,omitempty" json:"tx_id_0,omitempty"`
	Token1   string  `ic:"token_1" json:"token_1"`
	Amount1  idl.Nat `ic:"amount_1" json:"amount_1"`
	TxId1    *TxId   `ic:"tx_id_1,omitempty" json:"tx_id_1,omitempty"`
	LpFeeBps *uint8  `ic:"lp_fee_bps,omitempty" json:"lp_fee_bps,omitempty"`
}

type AddPoolReply struct {
	TxId             uint64            `ic:"tx_id" json:"tx_id"`
	PoolId           uint32            `ic:"pool_id" json:"pool_id"`
	RequestId        uint64            `ic:"request_id" json:"request_id"`
	Status           string            `ic:"status" json:"status"`
	Name             string            `ic:"name" json:"name"`
	Symbol           string            `ic:"symbol" json:"symbol"`
	Chain0           string            `ic:"chain_0" json:"chain_0"`
	Address0         string            `ic:"address_0" json:"address_0"`
	Symbol0          string            `ic:"symbol_0" json:"symbol_0"`
	Amount0          idl.Nat           `ic:"amount_0" json:"amount_0"`
	Chain1           string            `ic:"chain_1" json:"chain_1"`
	Address1         string            `ic:"address_1" json:"address_1"`
	Symbol1          string            `ic:"symbol_1" json:"symbol_1"`
	Amount1          idl.Nat           `ic:"amount_1" json:"amount_1"`
	LpFeeBps         uint8             `ic:"lp_fee_bps" json:"lp_fee_bps"`
	LpTokenSymbol    string            `ic:"lp_token_symbol" json:"lp_token_symbol"`
	AddLpTokenAmount idl.Nat           `ic:"add_lp_token_amount" json:"add_lp_token_amount"`
	TransferIds      []TransferIdReply `ic:"transfer_ids" json:"transfer_ids"`
	ClaimIds         []uint64          `ic:"claim_ids" json:"claim_ids"`
	IsRemoved        bool              `ic:"is_removed" json:"is_removed"`
	Ts               uint64            `ic:"ts" json:"ts"`
}

type AddPoolResult struct {
	Ok  *AddPoolReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string       `ic:"Err,variant" json:"Err,omitempty"`
}

type AddLiquidityAmountsReply struct {
	Symbol           string  `ic:"symbol" json:"symbol"`
	Chain0           string  `ic:"chain_0" json:"chain_0"`
	Address0         string  `ic:"address_0" json:"address_0"`
	Symbol0          string  `ic:"symbol_0" json:"symbol_0"`
	Amount0          idl.Nat `ic:"amount_0" json:"amount_0"`
	Fee0             idl.Nat `ic:"fee_0" json:"fee_0"`
	Chain1           string  `ic:"chain_1" json:"chain_1"`
	Address1         string  `ic:"address_1" json:"address_1"`
	Symbol1          string  `ic:"symbol_1" json:"symbol_1"`
	Amount1          idl.Nat `ic:"amount_1" json:"amount_1"`
	Fee1             idl.Nat `ic:"fee_1" json:"fee_1"`
	AddLpTokenAmount idl.Nat `ic:"add_lp_token_amount" json:"add_lp_token_amount"`
}

type AddLiquiditAmountsResult struct {
	Ok  *AddLiquidityAmountsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string                   `ic:"Err,variant" json:"Err,omitempty"`
}

type AddLiquidityArgs struct {
	Token0  string  `ic:"token_0" json:"token_0"`
	Amount0 idl.Nat `ic:"amount_0" json:"amount_0"`
	TxId0   *TxId   `ic:"tx_id_0,omitempty" json:"tx_id_0,omitempty"`
	Token1  string  `ic:"token_1" json:"token_1"`
	Amount1 idl.Nat `ic:"amount_1" json:"amount_1"`
	TxId1   *TxId   `ic:"tx_id_1,omitempty" json:"tx_id_1,omitempty"`
}

type AddLiquidityReply struct {
	TxId             uint64            `ic:"tx_id" json:"tx_id"`
	RequestId        uint64            `ic:"request_id" json:"request_id"`
	Status           string            `ic:"status" json:"status"`
	Symbol           string            `ic:"symbol" json:"symbol"`
	Chain0           string            `ic:"chain_0" json:"chain_0"`
	Address0         string            `ic:"address_0" json:"address_0"`
	Symbol0          string            `ic:"symbol_0" json:"symbol_0"`
	Amount0          idl.Nat           `ic:"amount_0" json:"amount_0"`
	Chain1           string            `ic:"chain_1" json:"chain_1"`
	Address1         string            `ic:"address_1" json:"address_1"`
	Symbol1          string            `ic:"symbol_1" json:"symbol_1"`
	Amount1          idl.Nat           `ic:"amount_1" json:"amount_1"`
	AddLpTokenAmount idl.Nat           `ic:"add_lp_token_amount" json:"add_lp_token_amount"`
	TransferIds      []TransferIdReply `ic:"transfer_ids" json:"transfer_ids"`
	ClaimIds         []uint64          `ic:"claim_ids" json:"claim_ids"`
	Ts               uint64            `ic:"ts" json:"ts"`
}

type AddLiquidityResult struct {
	Ok  *AddLiquidityReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string            `ic:"Err,variant" json:"Err,omitempty"`
}

type AddLiquidityAsyncResult struct {
	Ok  *uint64 `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
}

type ValidateAddLiquidityResult struct {
	Ok  *string `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveLiquidityAmountsReply struct {
	Symbol              string  `ic:"symbol" json:"symbol"`
	Chain0              string  `ic:"chain_0" json:"chain_0"`
	Address0            string  `ic:"address_0" json:"address_0"`
	Symbol0             string  `ic:"symbol_0" json:"symbol_0"`
	Amount0             idl.Nat `ic:"amount_0" json:"amount_0"`
	LpFee0              idl.Nat `ic:"lp_fee_0" json:"lp_fee_0"`
	Chain1              string  `ic:"chain_1" json:"chain_1"`
	Address1            string  `ic:"address_1" json:"address_1"`
	Symbol1             string  `ic:"symbol_1" json:"symbol_1"`
	Amount1             idl.Nat `ic:"amount_1" json:"amount_1"`
	LpFee1              idl.Nat `ic:"lp_fee_1" json:"lp_fee_1"`
	RemoveLpTokenAmount idl.Nat `ic:"remove_lp_token_amount" json:"remove_lp_token_amount"`
}

type RemoveLiquidityAmountsResult struct {
	Ok  *RemoveLiquidityAmountsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string                      `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveLiquidityArgs struct {
	Token0              string  `ic:"token_0" json:"token_0"`
	Token1              string  `ic:"token_1" json:"token_1"`
	RemoveLpTokenAmount idl.Nat `ic:"remove_lp_token_amount" json:"remove_lp_token_amount"`
}

type RemoveLiquidityReply struct {
	TxId                uint64            `ic:"tx_id" json:"tx_id"`
	RequestId           uint64            `ic:"request_id" json:"request_id"`
	Status              string            `ic:"status" json:"status"`
	Symbol              string            `ic:"symbol" json:"symbol"`
	Chain0              string            `ic:"chain_0" json:"chain_0"`
	Address0            string            `ic:"address_0" json:"address_0"`
	Symbol0             string            `ic:"symbol_0" json:"symbol_0"`
	Amount0             idl.Nat           `ic:"amount_0" json:"amount_0"`
	LpFee0              idl.Nat           `ic:"lp_fee_0" json:"lp_fee_0"`
	Chain1              string            `ic:"chain_1" json:"chain_1"`
	Address1            string            `ic:"address_1" json:"address_1"`
	Symbol1             string            `ic:"symbol_1" json:"symbol_1"`
	Amount1             idl.Nat           `ic:"amount_1" json:"amount_1"`
	LpFee1              idl.Nat           `ic:"lp_fee_1" json:"lp_fee_1"`
	RemoveLpTokenAmount idl.Nat           `ic:"remove_lp_token_amount" json:"remove_lp_token_amount"`
	TransferIds         []TransferIdReply `ic:"transfer_ids" json:"transfer_ids"`
	ClaimIds            []uint64          `ic:"claim_ids" json:"claim_ids"`
	Ts                  uint64            `ic:"ts" json:"ts"`
}

type RemoveLiquidityResult struct {
	Ok  *RemoveLiquidityReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string               `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveLiquidityAsyncResult struct {
	Ok  *uint64 `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
}

type ValidateRemoveLiquidityResult struct {
	Ok  *string `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
}

type SwapAmountsTxReply struct {
	PoolSymbol     string  `ic:"pool_symbol" json:"pool_symbol"`
	PayChain       string  `ic:"pay_chain" json:"pay_chain"`
	PaySymbol      string  `ic:"pay_symbol" json:"pay_symbol"`
	PayAddress     string  `ic:"pay_address" json:"pay_address"`
	PayAmount      idl.Nat `ic:"pay_amount" json:"pay_amount"`
	ReceiveChain   string  `ic:"receive_chain" json:"receive_chain"`
	ReceiveSymbol  string  `ic:"receive_symbol" json:"receive_symbol"`
	ReceiveAddress string  `ic:"receive_address" json:"receive_address"`
	ReceiveAmount  idl.Nat `ic:"receive_amount" json:"receive_amount"`
	Price          float64 `ic:"price" json:"price"`
	LpFee          idl.Nat `ic:"lp_fee" json:"lp_fee"`
	GasFee         idl.Nat `ic:"gas_fee" json:"gas_fee"`
}

type SwapAmountsReply struct {
	PayChain       string               `ic:"pay_chain" json:"pay_chain"`
	PaySymbol      string               `ic:"pay_symbol" json:"pay_symbol"`
	PayAddress     string               `ic:"pay_address" json:"pay_address"`
	PayAmount      idl.Nat              `ic:"pay_amount" json:"pay_amount"`
	ReceiveChain   string               `ic:"receive_chain" json:"receive_chain"`
	ReceiveSymbol  string               `ic:"receive_symbol" json:"receive_symbol"`
	ReceiveAddress string               `ic:"receive_address" json:"receive_address"`
	ReceiveAmount  idl.Nat              `ic:"receive_amount" json:"receive_amount"`
	Price          float64              `ic:"price" json:"price"`
	MidPrice       float64              `ic:"mid_price" json:"mid_price"`
	Slippage       float64              `ic:"slippage" json:"slippage"`
	Txs            []SwapAmountsTxReply `ic:"txs" json:"txs"`
}

type SwapAmountsResult struct {
	Ok  *SwapAmountsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string           `ic:"Err,variant" json:"Err,omitempty"`
}

type SwapArgs struct {
	PayToken       string   `ic:"pay_token" json:"pay_token"`
	PayAmount      idl.Nat  `ic:"pay_amount" json:"pay_amount"`
	PayTxId        *TxId    `ic:"pay_tx_id,omitempty" json:"pay_tx_id,omitempty"`
	ReceiveToken   string   `ic:"receive_token" json:"receive_token"`
	ReceiveAmount  *idl.Nat `ic:"receive_amount,omitempty" json:"receive_amount,omitempty"`
	ReceiveAddress *string  `ic:"receive_address,omitempty" json:"receive_address,omitempty"`
	MaxSlippage    *float64 `ic:"max_slippage,omitempty" json:"max_slippage,omitempty"`
	ReferredBy     *string  `ic:"referred_by,omitempty" json:"referred_by,omitempty"`
}

type SwapTxReply struct {
	PoolSymbol     string  `ic:"pool_symbol" json:"pool_symbol"`
	PayChain       string  `ic:"pay_chain" json:"pay_chain"`
	PayAddress     string  `ic:"pay_address" json:"pay_address"`
	PaySymbol      string  `ic:"pay_symbol" json:"pay_symbol"`
	PayAmount      idl.Nat `ic:"pay_amount" json:"pay_amount"`
	ReceiveChain   string  `ic:"receive_chain" json:"receive_chain"`
	ReceiveAddress string  `ic:"receive_address" json:"receive_address"`
	ReceiveSymbol  string  `ic:"receive_symbol" json:"receive_symbol"`
	ReceiveAmount  idl.Nat `ic:"receive_amount" json:"receive_amount"`
	Price          float64 `ic:"price" json:"price"`
	LpFee          idl.Nat `ic:"lp_fee" json:"lp_fee"`
	GasFee         idl.Nat `ic:"gas_fee" json:"gas_fee"`
	Ts             uint64  `ic:"ts" json:"ts"`
}

type SwapReply struct {
	TxId           uint64            `ic:"tx_id" json:"tx_id"`
	RequestId      uint64            `ic:"request_id" json:"request_id"`
	Status         string            `ic:"status" json:"status"`
	PayChain       string            `ic:"pay_chain" json:"pay_chain"`
	PayAddress     string            `ic:"pay_address" json:"pay_address"`
	PaySymbol      string            `ic:"pay_symbol" json:"pay_symbol"`
	PayAmount      idl.Nat           `ic:"pay_amount" json:"pay_amount"`
	ReceiveChain   string            `ic:"receive_chain" json:"receive_chain"`
	ReceiveAddress string            `ic:"receive_address" json:"receive_address"`
	ReceiveSymbol  string            `ic:"receive_symbol" json:"receive_symbol"`
	ReceiveAmount  idl.Nat           `ic:"receive_amount" json:"receive_amount"`
	MidPrice       float64           `ic:"mid_price" json:"mid_price"`
	Price          float64           `ic:"price" json:"price"`
	Slippage       float64           `ic:"slippage" json:"slippage"`
	Txs            []SwapTxReply     `ic:"txs" json:"txs"`
	TransferIds    []TransferIdReply `ic:"transfer_ids" json:"transfer_ids"`
	ClaimIds       []uint64          `ic:"claim_ids" json:"claim_ids"`
	Ts             uint64            `ic:"ts" json:"ts"`
}

type SwapResult struct {
	Ok  *SwapReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string    `ic:"Err,variant" json:"Err,omitempty"`
}

type SwapAsyncResult struct {
	Ok  *uint64 `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
}

type ClaimsReply struct {
	ClaimId    uint64  `ic:"claim_id" json:"claim_id"`
	Status     string  `ic:"status" json:"status"`
	Chain      string  `ic:"chain" json:"chain"`
	Symbol     string  `ic:"symbol" json:"symbol"`
	CanisterId *string `ic:"canister_id,omitempty" json:"canister_id,omitempty"`
	Amount     idl.Nat `ic:"amount" json:"amount"`
	Fee        idl.Nat `ic:"fee" json:"fee"`
	ToAddress  string  `ic:"to_address" json:"to_address"`
	Desc       string  `ic:"desc" json:"desc"`
	Ts         uint64  `ic:"ts" json:"ts"`
}

type ClaimsResult struct {
	Ok  *[]ClaimsReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string        `ic:"Err,variant" json:"Err,omitempty"`
}

type ClaimReply struct {
	ClaimId     uint64            `ic:"claim_id" json:"claim_id"`
	Status      string            `ic:"status" json:"status"`
	Chain       string            `ic:"chain" json:"chain"`
	Symbol      string            `ic:"symbol" json:"symbol"`
	CanisterId  *string           `ic:"canister_id,omitempty" json:"canister_id,omitempty"`
	Amount      idl.Nat           `ic:"amount" json:"amount"`
	Fee         idl.Nat           `ic:"fee" json:"fee"`
	ToAddress   string            `ic:"to_address" json:"to_address"`
	Desc        string            `ic:"desc" json:"desc"`
	TransferIds []TransferIdReply `ic:"transfer_ids" json:"transfer_ids"`
	Ts          uint64            `ic:"ts" json:"ts"`
}

type ClaimResult struct {
	Ok  *ClaimReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string     `ic:"Err,variant" json:"Err,omitempty"`
}

type SendArgs struct {
	Token     string  `ic:"token" json:"token"`
	Amount    idl.Nat `ic:"amount" json:"amount"`
	ToAddress string  `ic:"to_address" json:"to_address"`
}

type SendReply struct {
	TxId      uint64  `ic:"tx_id" json:"tx_id"`
	RequestId uint64  `ic:"request_id" json:"request_id"`
	Status    string  `ic:"status" json:"status"`
	Chain     string  `ic:"chain" json:"chain"`
	Symbol    string  `ic:"symbol" json:"symbol"`
	Amount    idl.Nat `ic:"amount" json:"amount"`
	ToAddress string  `ic:"to_address" json:"to_address"`
	Ts        uint64  `ic:"ts" json:"ts"`
}

type SendResult struct {
	Ok  *SendReply `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *string    `ic:"Err,variant" json:"Err,omitempty"`
}

type API interface {
	Swap(arg0 SwapArgs) (*SwapResult, error)
	SwapAmounts(arg0 string, arg1 idl.Nat, arg2 string) (*SwapAmountsResult, error)
}

// api is a client for the "kongswap" canister.
type api struct {
	*agent.Agent
	CanisterId principal.Principal
}

// NewAPI creates a new agent for the "kongswap" canister.
func NewAPI(canisterId icp.Principal, a *icp.Agent) (*api, error) {
	return &api{
		Agent:      a.Raw(),
		CanisterId: canisterId.Raw(),
	}, nil
}

// Icrc1Name calls the "icrc1_name" method on the "kongswap" canister.
func (a api) Icrc1Name() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_name",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc10SupportedStandards calls the "icrc10_supported_standards" method on the "kongswap" canister.
func (a api) Icrc10SupportedStandards() (*[]Icrc10SupportedStandards, error) {
	var r0 []Icrc10SupportedStandards
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc10_supported_standards",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc28TrustedOrigins calls the "icrc28_trusted_origins" method on the "kongswap" canister.
func (a api) Icrc28TrustedOrigins() (*Icrc28TrustedOriginsResponse, error) {
	var r0 Icrc28TrustedOriginsResponse
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc28_trusted_origins",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Tokens calls the "tokens" method on the "kongswap" canister.
func (a api) Tokens(arg0 *string) (*TokensResult, error) {
	var r0 TokensResult
	if err := a.Agent.Query(
		a.CanisterId,
		"tokens",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Pools calls the "pools" method on the "kongswap" canister.
func (a api) Pools(arg0 *string) (*PoolsResult, error) {
	var r0 PoolsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"pools",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUser calls the "get_user" method on the "kongswap" canister.
func (a api) GetUser() (*UserResult, error) {
	var r0 UserResult
	if err := a.Agent.Query(
		a.CanisterId,
		"get_user",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// UserBalances calls the "user_balances" method on the "kongswap" canister.
func (a api) UserBalances(arg0 string) (*UserBalancesResult, error) {
	var r0 UserBalancesResult
	if err := a.Agent.Query(
		a.CanisterId,
		"user_balances",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Requests calls the "requests" method on the "kongswap" canister.
func (a api) Requests(arg0 *uint64) (*RequestsResult, error) {
	var r0 RequestsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"requests",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AddToken calls the "add_token" method on the "kongswap" canister.
func (a api) AddToken(arg0 AddTokenArgs) (*AddTokenResult, error) {
	var r0 AddTokenResult
	if err := a.Agent.Call(
		a.CanisterId,
		"add_token",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// UpdateToken calls the "update_token" method on the "kongswap" canister.
func (a api) UpdateToken(arg0 UpdateTokenArgs) (*UpdateTokenResult, error) {
	var r0 UpdateTokenResult
	if err := a.Agent.Call(
		a.CanisterId,
		"update_token",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AddPool calls the "add_pool" method on the "kongswap" canister.
func (a api) AddPool(arg0 AddPoolArgs) (*AddPoolResult, error) {
	var r0 AddPoolResult
	if err := a.Agent.Call(
		a.CanisterId,
		"add_pool",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AddLiquidityAmounts calls the "add_liquidity_amounts" method on the "kongswap" canister.
func (a api) AddLiquidityAmounts(arg0 string, arg1 idl.Nat, arg2 string) (*AddLiquiditAmountsResult, error) {
	var r0 AddLiquiditAmountsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"add_liquidity_amounts",
		[]any{arg0, arg1, arg2},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AddLiquidity calls the "add_liquidity" method on the "kongswap" canister.
func (a api) AddLiquidity(arg0 AddLiquidityArgs) (*AddLiquidityResult, error) {
	var r0 AddLiquidityResult
	if err := a.Agent.Call(
		a.CanisterId,
		"add_liquidity",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AddLiquidityAsync calls the "add_liquidity_async" method on the "kongswap" canister.
func (a api) AddLiquidityAsync(arg0 AddLiquidityArgs) (*AddLiquidityAsyncResult, error) {
	var r0 AddLiquidityAsyncResult
	if err := a.Agent.Call(
		a.CanisterId,
		"add_liquidity_async",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// ValidateAddLiquidity calls the "validate_add_liquidity" method on the "kongswap" canister.
func (a api) ValidateAddLiquidity() (*ValidateAddLiquidityResult, error) {
	var r0 ValidateAddLiquidityResult
	if err := a.Agent.Call(
		a.CanisterId,
		"validate_add_liquidity",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RemoveLiquidityAmounts calls the "remove_liquidity_amounts" method on the "kongswap" canister.
func (a api) RemoveLiquidityAmounts(arg0 string, arg1 string, arg2 idl.Nat) (*RemoveLiquidityAmountsResult, error) {
	var r0 RemoveLiquidityAmountsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"remove_liquidity_amounts",
		[]any{arg0, arg1, arg2},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RemoveLiquidity calls the "remove_liquidity" method on the "kongswap" canister.
func (a api) RemoveLiquidity(arg0 RemoveLiquidityArgs) (*RemoveLiquidityResult, error) {
	var r0 RemoveLiquidityResult
	if err := a.Agent.Call(
		a.CanisterId,
		"remove_liquidity",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RemoveLiquidityAsync calls the "remove_liquidity_async" method on the "kongswap" canister.
func (a api) RemoveLiquidityAsync(arg0 RemoveLiquidityArgs) (*RemoveLiquidityAsyncResult, error) {
	var r0 RemoveLiquidityAsyncResult
	if err := a.Agent.Call(
		a.CanisterId,
		"remove_liquidity_async",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// ValidateRemoveLiquidity calls the "validate_remove_liquidity" method on the "kongswap" canister.
func (a api) ValidateRemoveLiquidity() (*ValidateRemoveLiquidityResult, error) {
	var r0 ValidateRemoveLiquidityResult
	if err := a.Agent.Call(
		a.CanisterId,
		"validate_remove_liquidity",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SwapAmounts calls the "swap_amounts" method on the "kongswap" canister.
func (a api) SwapAmounts(arg0 string, arg1 idl.Nat, arg2 string) (*SwapAmountsResult, error) {
	var r0 SwapAmountsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"swap_amounts",
		[]any{arg0, arg1, arg2},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Swap calls the "swap" method on the "kongswap" canister.
func (a api) Swap(arg0 SwapArgs) (*SwapResult, error) {
	var r0 SwapResult
	if err := a.Agent.Call(
		a.CanisterId,
		"swap",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SwapAsync calls the "swap_async" method on the "kongswap" canister.
func (a api) SwapAsync(arg0 SwapArgs) (*SwapAsyncResult, error) {
	var r0 SwapAsyncResult
	if err := a.Agent.Call(
		a.CanisterId,
		"swap_async",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Claims calls the "claims" method on the "kongswap" canister.
func (a api) Claims(arg0 string) (*ClaimsResult, error) {
	var r0 ClaimsResult
	if err := a.Agent.Query(
		a.CanisterId,
		"claims",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Claim calls the "claim" method on the "kongswap" canister.
func (a api) Claim(arg0 uint64) (*ClaimResult, error) {
	var r0 ClaimResult
	if err := a.Agent.Call(
		a.CanisterId,
		"claim",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Send calls the "send" method on the "kongswap" canister.
func (a api) Send(arg0 SendArgs) (*SendResult, error) {
	var r0 SendResult
	if err := a.Agent.Call(
		a.CanisterId,
		"send",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// CheckPools calls the "check_pools" method on the "kongswap" canister.
func (a api) CheckPools() (*CheckPoolsResult, error) {
	var r0 CheckPoolsResult
	if err := a.Agent.Call(
		a.CanisterId,
		"check_pools",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}
