// Package ntn provides a client for the "ntn" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package ntnswap

import (
	"fmt"

	"github.com/aviate-labs/agent-go/candid/idl"
	"github.com/aviate-labs/agent-go/principal"
	"github.com/niccolofant/ic-arb/core/icp"
)

type Version struct {
	Alpha   *[]uint16 `ic:"alpha,variant" json:"alpha,omitempty"`
	Beta    *[]uint16 `ic:"beta,variant" json:"beta,omitempty"`
	Release *[]uint16 `ic:"release,variant" json:"release,omitempty"`
}

type ValueMap struct {
	Field0 string `ic:"0,tuple" json:"0,tuple"`
	Field1 Value  `ic:"1,tuple" json:"1,tuple"`
}

type Value struct {
	Array *[]Value    `ic:"Array,variant" json:"Array,omitempty"`
	Blob  *[]byte     `ic:"Blob,variant" json:"Blob,omitempty"`
	Int   *idl.Int    `ic:"Int,variant" json:"Int,omitempty"`
	Map   *[]ValueMap `ic:"Map,variant" json:"Map,omitempty"`
	Nat   *idl.Nat    `ic:"Nat,variant" json:"Nat,omitempty"`
	Text  *string     `ic:"Text,variant" json:"Text,omitempty"`
}

type ValidationResult struct {
	Err *string `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *string `ic:"Ok,variant" json:"Ok,omitempty"`
}

type TransferResponse struct {
	Err *string `ic:"err,variant" json:"err,omitempty"`
	Ok  *uint64 `ic:"ok,variant" json:"ok,omitempty"`
}

type TransferRequest struct {
	Amount idl.Nat `ic:"amount" json:"amount"`
	From   struct {
		Account *Account `ic:"account,variant" json:"account,omitempty"`
		Node    *struct {
			EndpointIdx EndpointIdx `ic:"endpoint_idx" json:"endpoint_idx"`
			NodeId      LocalNodeId `ic:"node_id" json:"node_id"`
		} `ic:"node,variant" json:"node,omitempty"`
	} `ic:"from" json:"from"`
	Ledger SupportedLedger `ic:"ledger" json:"ledger"`
	Memo   *[]byte         `ic:"memo,omitempty" json:"memo,omitempty"`
	To     struct {
		Account         *Account `ic:"account,variant" json:"account,omitempty"`
		ExternalAccount *struct {
			Ic    *Account `ic:"ic,variant" json:"ic,omitempty"`
			Icp   *[]byte  `ic:"icp,variant" json:"icp,omitempty"`
			Other *[]byte  `ic:"other,variant" json:"other,omitempty"`
		} `ic:"external_account,variant" json:"external_account,omitempty"`
		Node *struct {
			EndpointIdx EndpointIdx `ic:"endpoint_idx" json:"endpoint_idx"`
			NodeId      LocalNodeId `ic:"node_id" json:"node_id"`
		} `ic:"node,variant" json:"node,omitempty"`
		NodeBilling *LocalNodeId `ic:"node_billing,variant" json:"node_billing,omitempty"`
		Temp        *struct {
			Id        uint32      `ic:"id" json:"id"`
			SourceIdx EndpointIdx `ic:"source_idx" json:"source_idx"`
		} `ic:"temp,variant" json:"temp,omitempty"`
	} `ic:"to" json:"to"`
}

type TransactionShared struct {
	Amount         idl.Nat `ic:"amount" json:"amount"`
	CreatedAtTime  uint64  `ic:"created_at_time" json:"created_at_time"`
	FromSubaccount *[]byte `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	Id             struct {
		Blob *[]byte `ic:""blob",variant" json:""blob",omitempty"`
		N64  *uint64 `ic:"n64,variant" json:"n64,omitempty"`
	} `ic:"id" json:"id"`
	Memo  []byte       `ic:"memo" json:"memo"`
	To    AccountMixed `ic:"to" json:"to"`
	Tries idl.Nat      `ic:"tries" json:"tries"`
}

type TransactionRange struct {
	Length idl.Nat `ic:"length" json:"length"`
	Start  idl.Nat `ic:"start" json:"start"`
}

type TokenId struct {
	Path     PlatformPath `ic:"path" json:"path"`
	Platform PlatformId   `ic:"platform" json:"platform"`
}

type TokenData struct {
	Volume24    Amount `ic:"volume24" json:"volume24"`
	VolumeTotal Amount `ic:"volume_total" json:"volume_total"`
}

type SwapResponse struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type SwapRequest struct {
	Account      Account         `ic:"account" json:"account"`
	Amount       idl.Nat         `ic:"amount" json:"amount"`
	LedgerFrom   SupportedLedger `ic:"ledger_from" json:"ledger_from"`
	LedgerTo     SupportedLedger `ic:"ledger_to" json:"ledger_to"`
	MinAmountOut idl.Nat         `ic:"min_amount_out" json:"min_amount_out"`
}

type Swap struct {
	AmountIn   idl.Nat `ic:"amountIn" json:"amountIn"`
	AmountOut  idl.Nat `ic:"amountOut" json:"amountOut"`
	From       Account `ic:"from" json:"from"`
	NewPrice   float64 `ic:"newPrice" json:"newPrice"`
	To         Account `ic:"to" json:"to"`
	ZeroForOne bool    `ic:"zeroForOne" json:"zeroForOne"`
}

type SupportedLedger struct {
	Ic    *principal.Principal `ic:"ic,variant" json:"ic,omitempty"`
	Other *struct {
		Ledger   []byte `ic:"ledger" json:"ledger"`
		Platform uint64 `ic:"platform" json:"platform"`
	} `ic:"other,variant" json:"other,omitempty"`
}

type SourceEndpointResp struct {
	Balance  idl.Nat  `ic:"balance" json:"balance"`
	Endpoint Endpoint `ic:"endpoint" json:"endpoint"`
	Name     string   `ic:"name" json:"name"`
}

type Shared8 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
	} `ic:"internals" json:"internals"`
	Variables struct {
		Description string `ic:"description" json:"description"`
	} `ic:"variables" json:"variables"`
}

type Shared7 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		WaitUntilTs uint64 `ic:"wait_until_ts" json:"wait_until_ts"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		IntervalSec NumVariant `ic:"interval_sec" json:"interval_sec"`
		MaxAmount   NumVariant `ic:"max_amount" json:"max_amount"`
	} `ic:"variables" json:"variables"`
}

type Shared6 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		CurrentSource idl.Nat `ic:"current_source" json:"current_source"`
		NextSendTs    uint64  `ic:"next_send_ts" json:"next_send_ts"`
		NextSwitchTs  uint64  `ic:"next_switch_ts" json:"next_switch_ts"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		AmountA          NumVariant `ic:"amount_a" json:"amount_a"`
		AmountB          NumVariant `ic:"amount_b" json:"amount_b"`
		SwitchChance     uint64     `ic:"switch_chance" json:"switch_chance"`
		SwitchInterval   NumVariant `ic:"switch_interval" json:"switch_interval"`
		ThrottleInterval NumVariant `ic:"throttle_interval" json:"throttle_interval"`
	} `ic:"variables" json:"variables"`
}

type Shared5 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
	} `ic:"internals" json:"internals"`
	Variables struct {
		Split []idl.Nat `ic:"split" json:"split"`
	} `ic:"variables" json:"variables"`
}

type Shared4 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		AddedTokenA idl.Nat `ic:"addedTokenA" json:"addedTokenA"`
		AddedTokenB idl.Nat `ic:"addedTokenB" json:"addedTokenB"`
		LastError   *string `ic:"last_error,omitempty" json:"last_error,omitempty"`
		LastRun     uint64  `ic:"last_run" json:"last_run"`
		TokenA      idl.Nat `ic:"tokenA" json:"tokenA"`
		TokenB      idl.Nat `ic:"tokenB" json:"tokenB"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		Flow  Flow  `ic:"flow" json:"flow"`
		Range Range `ic:"range" json:"range"`
	} `ic:"variables" json:"variables"`
}

type Shared3 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		CurrentRate *float64 `ic:"current_rate,omitempty" json:"current_rate,omitempty"`
		LastBuy     uint64   `ic:"last_buy" json:"last_buy"`
		LastError   *string  `ic:"last_error,omitempty" json:"last_error,omitempty"`
		LastRun     uint64   `ic:"last_run" json:"last_run"`
		NextBuy     uint64   `ic:"next_buy" json:"next_buy"`
		Price       *float64 `ic:"price,omitempty" json:"price,omitempty"`
		SwapFeeE4s  idl.Nat  `ic:"swap_fee_e4s" json:"swap_fee_e4s"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		BuyForAmount       idl.Nat  `ic:"buy_for_amount" json:"buy_for_amount"`
		BuyIntervalSeconds uint64   `ic:"buy_interval_seconds" json:"buy_interval_seconds"`
		MaxImpact          float64  `ic:"max_impact" json:"max_impact"`
		MaxRate            *float64 `ic:"max_rate,omitempty" json:"max_rate,omitempty"`
	} `ic:"variables" json:"variables"`
}

type Shared2 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		CurrentRatios []float64 `ic:"current_ratios" json:"current_ratios"`
		LastError     *string   `ic:"last_error,omitempty" json:"last_error,omitempty"`
		LastRebalance uint64    `ic:"last_rebalance" json:"last_rebalance"`
		LastRemove    uint64    `ic:"last_remove" json:"last_remove"`
		LastRun       uint64    `ic:"last_run" json:"last_run"`
		TotalValueUsd float64   `ic:"total_value_usd" json:"total_value_usd"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		PriceLedgerId            principal.Principal `ic:"price_ledger_id" json:"price_ledger_id"`
		RebalanceIntervalSeconds uint64              `ic:"rebalance_interval_seconds" json:"rebalance_interval_seconds"`
		RemoveAmountUsd          idl.Nat             `ic:"remove_amount_usd" json:"remove_amount_usd"`
		RemoveIntervalSeconds    uint64              `ic:"remove_interval_seconds" json:"remove_interval_seconds"`
		SwapAmountUsd            idl.Nat             `ic:"swap_amount_usd" json:"swap_amount_usd"`
		ThresholdPercent         float64             `ic:"threshold_percent" json:"threshold_percent"`
		TokenRatios              []idl.Nat           `ic:"token_ratios" json:"token_ratios"`
	} `ic:"variables" json:"variables"`
}

type Shared1 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Internals struct {
		AddedTokenA  idl.Nat  `ic:"addedTokenA" json:"addedTokenA"`
		AddedTokenB  idl.Nat  `ic:"addedTokenB" json:"addedTokenB"`
		CurrentPrice *float64 `ic:"current_price,omitempty" json:"current_price,omitempty"`
		LastError    *string  `ic:"last_error,omitempty" json:"last_error,omitempty"`
		LastRun      uint64   `ic:"last_run" json:"last_run"`
		TokenA       idl.Nat  `ic:"tokenA" json:"tokenA"`
		TokenB       idl.Nat  `ic:"tokenB" json:"tokenB"`
	} `ic:"internals" json:"internals"`
	Variables struct {
		IntervalSeconds uint64  `ic:"interval_seconds" json:"interval_seconds"`
		Mode            Mode    `ic:"mode" json:"mode"`
		RangePercent    float64 `ic:"range_percent" json:"range_percent"`
		RemovePercent   float64 `ic:"remove_percent" json:"remove_percent"`
	} `ic:"variables" json:"variables"`
}

type Shared struct {
	AutoLiquidity     *Shared1 `ic:"auto_liquidity,variant" json:"auto_liquidity,omitempty"`
	Balancer          *Shared2 `ic:"balancer,variant" json:"balancer,omitempty"`
	Exchange          *Shared3 `ic:"exchange,variant" json:"exchange,omitempty"`
	ExchangeLiquidity *Shared4 `ic:"exchange_liquidity,variant" json:"exchange_liquidity,omitempty"`
	Split             *Shared5 `ic:"split,variant" json:"split,omitempty"`
	Switcher          *Shared6 `ic:"switcher,variant" json:"switcher,omitempty"`
	Throttle          *Shared7 `ic:"throttle,variant" json:"throttle,omitempty"`
	Vault             *Shared8 `ic:"vault,variant" json:"vault,omitempty"`
}

type Sent struct {
	Amount idl.Nat             `ic:"amount" json:"amount"`
	Ledger principal.Principal `ic:"ledger" json:"ledger"`
	To     struct {
		Icp  *[]byte  `ic:"icp,variant" json:"icp,omitempty"`
		Icrc *Account `ic:"icrc,variant" json:"icrc,omitempty"`
	} `ic:"to" json:"to"`
}

type SETTINGS struct {
	ALLOWTEMPNODECREATION       bool         `ic:"ALLOW_TEMP_NODE_CREATION" json:"ALLOW_TEMP_NODE_CREATION"`
	BILLING                     BillingPylon `ic:"BILLING" json:"BILLING"`
	MAXINSTRUCTIONSPERHEARTBEAT uint64       `ic:"MAX_INSTRUCTIONS_PER_HEARTBEAT" json:"MAX_INSTRUCTIONS_PER_HEARTBEAT"`
	PYLONGOVERNEDBY             string       `ic:"PYLON_GOVERNED_BY" json:"PYLON_GOVERNED_BY"`
	PYLONNAME                   string       `ic:"PYLON_NAME" json:"PYLON_NAME"`
	REQUESTMAXEXPIRESEC         uint64       `ic:"REQUEST_MAX_EXPIRE_SEC" json:"REQUEST_MAX_EXPIRE_SEC"`
	TEMPNODEEXPIRATIONSEC       uint64       `ic:"TEMP_NODE_EXPIRATION_SEC" json:"TEMP_NODE_EXPIRATION_SEC"`
}

type Result struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type Received struct {
	Amount idl.Nat `ic:"amount" json:"amount"`
	From   struct {
		Icp  *[]byte  `ic:"icp,variant" json:"icp,omitempty"`
		Icrc *Account `ic:"icrc,variant" json:"icrc,omitempty"`
	} `ic:"from" json:"from"`
	Ledger principal.Principal `ic:"ledger" json:"ledger"`
}

type Rate = float64

type Range struct {
	Partial *struct {
		FromPrice float64 `ic:"from_price" json:"from_price"`
		ToPrice   float64 `ic:"to_price" json:"to_price"`
	} `ic:"partial,variant" json:"partial,omitempty"`
}

type QuoteResponse struct {
	Err *string `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		AfterPrice  float64 `ic:"after_price" json:"after_price"`
		AmountInMax idl.Nat `ic:"amount_in_max" json:"amount_in_max"`
		AmountOut   idl.Nat `ic:"amount_out" json:"amount_out"`
		BeforePrice float64 `ic:"before_price" json:"before_price"`
		Fees        []struct {
			Field0 string          `ic:"0,tuple" json:"0,tuple"`
			Field1 SupportedLedger `ic:"1,tuple" json:"1,tuple"`
			Field2 idl.Nat         `ic:"2,tuple" json:"2,tuple"`
		} `ic:"fees" json:"fees"`
		Path []struct {
			Field0 SupportedLedger `ic:"0,tuple" json:"0,tuple"`
			Field1 float64         `ic:"1,tuple" json:"1,tuple"`
		} `ic:"path" json:"path"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type QuoteRequest struct {
	Amount     idl.Nat         `ic:"amount" json:"amount"`
	LedgerFrom SupportedLedger `ic:"ledger_from" json:"ledger_from"`
	LedgerTo   SupportedLedger `ic:"ledger_to" json:"ledger_to"`
}

type PylonMetaResp struct {
	Billing             BillingPylon `ic:"billing" json:"billing"`
	GovernedBy          string       `ic:"governed_by" json:"governed_by"`
	Modules             []ModuleMeta `ic:"modules" json:"modules"`
	Name                string       `ic:"name" json:"name"`
	RequestMaxExpireSec uint64       `ic:"request_max_expire_sec" json:"request_max_expire_sec"`
	SupportedLedgers    []LedgerInfo `ic:"supported_ledgers" json:"supported_ledgers"`
	TemporaryNodes      struct {
		Allowed   bool   `ic:"allowed" json:"allowed"`
		ExpireSec uint64 `ic:"expire_sec" json:"expire_sec"`
	} `ic:"temporary_nodes" json:"temporary_nodes"`
}

type PoolResponse struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type PoolRequest struct {
	Base  principal.Principal `ic:"base" json:"base"`
	Quote principal.Principal `ic:"quote" json:"quote"`
}

type PlatformPath = []byte

type PlatformId = uint64

type PendingTransactions struct {
	Id           principal.Principal `ic:"id" json:"id"`
	Transactions []TransactionShared `ic:"transactions" json:"transactions"`
}

type PairResponseOk = []PairData

type PairResponseErr struct {
	InvalidDepthLevel *Level  `ic:"InvalidDepthLevel,variant" json:"InvalidDepthLevel,omitempty"`
	InvalidDepthLimit *uint32 `ic:"InvalidDepthLimit,variant" json:"InvalidDepthLimit,omitempty"`
	NotFound          *PairId `ic:"NotFound,variant" json:"NotFound,omitempty"`
}

type PairResponse struct {
	Err *PairResponseErr `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *PairResponseOk  `ic:"Ok,variant" json:"Ok,omitempty"`
}

type PairRequest struct {
	Depth *DepthRequest `ic:"depth,omitempty" json:"depth,omitempty"`
	Pairs []PairId      `ic:"pairs" json:"pairs"`
}

type PairInfo struct {
	Data DataSource `ic:"data" json:"data"`
	Id   PairId     `ic:"id" json:"id"`
}

type PairId struct {
	Base  TokenId `ic:"base" json:"base"`
	Quote TokenId `ic:"quote" json:"quote"`
}

type PairData struct {
	Asks []struct {
		Field0 Rate   `ic:"0,tuple" json:"0,tuple"`
		Field1 Amount `ic:"1,tuple" json:"1,tuple"`
	} `ic:"asks" json:"asks"`
	Base TokenData `ic:"base" json:"base"`
	Bids []struct {
		Field0 Rate   `ic:"0,tuple" json:"0,tuple"`
		Field1 Amount `ic:"1,tuple" json:"1,tuple"`
	} `ic:"bids" json:"bids"`
	Id               PairId    `ic:"id" json:"id"`
	Last             Rate      `ic:"last" json:"last"`
	LastTimestamp    uint64    `ic:"last_timestamp" json:"last_timestamp"`
	Quote            TokenData `ic:"quote" json:"quote"`
	UpdatedTimestamp uint64    `ic:"updated_timestamp" json:"updated_timestamp"`
	Volume24USD      *Amount   `ic:"volume24_USD,omitempty" json:"volume24_USD,omitempty"`
	VolumeTotalUSD   *Amount   `ic:"volume_total_USD,omitempty" json:"volume_total_USD,omitempty"`
}

type OHLCVResponse struct {
	Err *string `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		Data []MarketTickInner `ic:"data" json:"data"`
		L1   SupportedLedger   `ic:"l1" json:"l1"`
		L2   SupportedLedger   `ic:"l2" json:"l2"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type OHLCVRequest struct {
	L1     SupportedLedger `ic:"l1" json:"l1"`
	L2     SupportedLedger `ic:"l2" json:"l2"`
	Period struct {
		T1d *idl.Null `ic:"t1d,variant" json:"t1d,omitempty"`
		T1h *idl.Null `ic:"t1h,variant" json:"t1h,omitempty"`
		T1m *idl.Null `ic:"t1m,variant" json:"t1m,omitempty"`
		T1s *idl.Null `ic:"t1s,variant" json:"t1s,omitempty"`
	} `ic:"period" json:"period"`
}

type NumVariant struct {
	Fixed *uint64 `ic:"fixed,variant" json:"fixed,omitempty"`
	Rnd   *struct {
		Max uint64 `ic:"max" json:"max"`
		Min uint64 `ic:"min" json:"min"`
	} `ic:"rnd,variant" json:"rnd,omitempty"`
}

type NodeShared struct {
	Active  bool `ic:"active" json:"active"`
	Billing struct {
		Account        Account               `ic:"account" json:"account"`
		BillingOption  idl.Nat               `ic:"billing_option" json:"billing_option"`
		CostPerDay     idl.Nat               `ic:"cost_per_day" json:"cost_per_day"`
		CurrentBalance idl.Nat               `ic:"current_balance" json:"current_balance"`
		Expires        *uint64               `ic:"expires,omitempty" json:"expires,omitempty"`
		Frozen         bool                  `ic:"frozen" json:"frozen"`
		TransactionFee BillingTransactionFee `ic:"transaction_fee" json:"transaction_fee"`
	} `ic:"billing" json:"billing"`
	Controllers  []Controller              `ic:"controllers" json:"controllers"`
	Created      uint64                    `ic:"created" json:"created"`
	Custom       *Shared                   `ic:"custom,omitempty" json:"custom,omitempty"`
	Destinations []DestinationEndpointResp `ic:"destinations" json:"destinations"`
	Extractors   []LocalNodeId             `ic:"extractors" json:"extractors"`
	Id           LocalNodeId               `ic:"id" json:"id"`
	Modified     uint64                    `ic:"modified" json:"modified"`
	Refund       Account                   `ic:"refund" json:"refund"`
	Sources      []SourceEndpointResp      `ic:"sources" json:"sources"`
}

type ModuleMeta struct {
	Author           string               `ic:"author" json:"author"`
	AuthorAccount    Account              `ic:"author_account" json:"author_account"`
	Billing          []Billing            `ic:"billing" json:"billing"`
	CreateAllowed    bool                 `ic:"create_allowed" json:"create_allowed"`
	Description      string               `ic:"description" json:"description"`
	Destinations     EndpointsDescription `ic:"destinations" json:"destinations"`
	Id               string               `ic:"id" json:"id"`
	LedgerSlots      []string             `ic:"ledger_slots" json:"ledger_slots"`
	Name             string               `ic:"name" json:"name"`
	Sources          EndpointsDescription `ic:"sources" json:"sources"`
	SupportedLedgers []SupportedLedger    `ic:"supported_ledgers" json:"supported_ledgers"`
	TemporaryAllowed bool                 `ic:"temporary_allowed" json:"temporary_allowed"`
	Version          Version              `ic:"version" json:"version"`
}

type ModifyRequest8 struct {
	Description string `ic:"description" json:"description"`
}

type ModifyRequest7 struct {
	IntervalSec NumVariant `ic:"interval_sec" json:"interval_sec"`
	MaxAmount   NumVariant `ic:"max_amount" json:"max_amount"`
}

type ModifyRequest6 struct {
	AmountA          NumVariant `ic:"amount_a" json:"amount_a"`
	AmountB          NumVariant `ic:"amount_b" json:"amount_b"`
	SwitchChance     uint64     `ic:"switch_chance" json:"switch_chance"`
	SwitchInterval   NumVariant `ic:"switch_interval" json:"switch_interval"`
	ThrottleInterval NumVariant `ic:"throttle_interval" json:"throttle_interval"`
}

type ModifyRequest5 struct {
	Split []idl.Nat `ic:"split" json:"split"`
}

type ModifyRequest4 struct {
	Flow  Flow  `ic:"flow" json:"flow"`
	Range Range `ic:"range" json:"range"`
}

type ModifyRequest3 struct {
	BuyForAmount       idl.Nat  `ic:"buy_for_amount" json:"buy_for_amount"`
	BuyIntervalSeconds uint64   `ic:"buy_interval_seconds" json:"buy_interval_seconds"`
	MaxImpact          float64  `ic:"max_impact" json:"max_impact"`
	MaxRate            *float64 `ic:"max_rate,omitempty" json:"max_rate,omitempty"`
}

type ModifyRequest2 struct {
	PriceLedgerId            principal.Principal `ic:"price_ledger_id" json:"price_ledger_id"`
	RebalanceIntervalSeconds uint64              `ic:"rebalance_interval_seconds" json:"rebalance_interval_seconds"`
	RemoveAmountUsd          idl.Nat             `ic:"remove_amount_usd" json:"remove_amount_usd"`
	RemoveIntervalSeconds    uint64              `ic:"remove_interval_seconds" json:"remove_interval_seconds"`
	SwapAmountUsd            idl.Nat             `ic:"swap_amount_usd" json:"swap_amount_usd"`
	ThresholdPercent         float64             `ic:"threshold_percent" json:"threshold_percent"`
	TokenRatios              []idl.Nat           `ic:"token_ratios" json:"token_ratios"`
}

type ModifyRequest1 struct {
	IntervalSeconds uint64  `ic:"interval_seconds" json:"interval_seconds"`
	Mode            Mode    `ic:"mode" json:"mode"`
	RangePercent    float64 `ic:"range_percent" json:"range_percent"`
	RemovePercent   float64 `ic:"remove_percent" json:"remove_percent"`
}

type ModifyRequest struct {
	AutoLiquidity     *ModifyRequest1 `ic:"auto_liquidity,variant" json:"auto_liquidity,omitempty"`
	Balancer          *ModifyRequest2 `ic:"balancer,variant" json:"balancer,omitempty"`
	Exchange          *ModifyRequest3 `ic:"exchange,variant" json:"exchange,omitempty"`
	ExchangeLiquidity *ModifyRequest4 `ic:"exchange_liquidity,variant" json:"exchange_liquidity,omitempty"`
	Split             *ModifyRequest5 `ic:"split,variant" json:"split,omitempty"`
	Switcher          *ModifyRequest6 `ic:"switcher,variant" json:"switcher,omitempty"`
	Throttle          *ModifyRequest7 `ic:"throttle,variant" json:"throttle,omitempty"`
	Vault             *ModifyRequest8 `ic:"vault,variant" json:"vault,omitempty"`
}

type ModifyNodeResponse struct {
	Err *string          `ic:"err,variant" json:"err,omitempty"`
	Ok  *GetNodeResponse `ic:"ok,variant" json:"ok,omitempty"`
}

type ModifyNodeRequest struct {
	Field0 LocalNodeId          `ic:"0,tuple" json:"0,tuple"`
	Field1 *CommonModifyRequest `ic:"1,tuple,omitempty" json:"1,tuple,omitempty"`
	Field2 *ModifyRequest       `ic:"2,tuple,omitempty" json:"2,tuple,omitempty"`
}

type Mode struct {
	Auto   *idl.Null `ic:"auto,variant" json:"auto,omitempty"`
	Remove *idl.Null `ic:"remove,variant" json:"remove,omitempty"`
}

type MarketTickInner struct {
	Field0 uint32  `ic:"0,tuple" json:"0,tuple"`
	Field1 float64 `ic:"1,tuple" json:"1,tuple"`
	Field2 float64 `ic:"2,tuple" json:"2,tuple"`
	Field3 float64 `ic:"3,tuple" json:"3,tuple"`
	Field4 float64 `ic:"4,tuple" json:"4,tuple"`
	Field5 idl.Nat `ic:"5,tuple" json:"5,tuple"`
}

type LocalNodeId = uint32

type ListPairsResponse = []PairInfo

type LiquidityRemove struct {
	AmountA idl.Nat `ic:"amountA" json:"amountA"`
	AmountB idl.Nat `ic:"amountB" json:"amountB"`
	From    Account `ic:"from" json:"from"`
	ToA     Account `ic:"toA" json:"toA"`
	ToB     Account `ic:"toB" json:"toB"`
}

type LiquidityAdd struct {
	AmountA idl.Nat `ic:"amountA" json:"amountA"`
	AmountB idl.Nat `ic:"amountB" json:"amountB"`
	FromA   Account `ic:"fromA" json:"fromA"`
	FromB   Account `ic:"fromB" json:"fromB"`
	To      Account `ic:"to" json:"to"`
}

type Level = uint8

type LedgerLabel = string

type LedgerInfo1 struct {
	Id   principal.Principal `ic:"id" json:"id"`
	Info struct {
		Icp  *Info `ic:"icp,variant" json:"icp,omitempty"`
		Icrc *Info `ic:"icrc,variant" json:"icrc,omitempty"`
	} `ic:"info" json:"info"`
}

type LedgerInfo struct {
	Decimals uint8           `ic:"decimals" json:"decimals"`
	Fee      idl.Nat         `ic:"fee" json:"fee"`
	Ledger   SupportedLedger `ic:"ledger" json:"ledger"`
	Name     string          `ic:"name" json:"name"`
	Symbol   string          `ic:"symbol" json:"symbol"`
}

type LedgerIdx = idl.Nat

type InputAddress struct {
	Ic    *Account `ic:"ic,variant" json:"ic,omitempty"`
	Other *[]byte  `ic:"other,variant" json:"other,omitempty"`
	Temp  *struct {
		Id        uint32      `ic:"id" json:"id"`
		SourceIdx EndpointIdx `ic:"source_idx" json:"source_idx"`
	} `ic:"temp,variant" json:"temp,omitempty"`
}

type Info struct {
	Accounts               idl.Nat             `ic:"accounts" json:"accounts"`
	ActorPrincipal         principal.Principal `ic:"actor_principal" json:"actor_principal"`
	Errors                 idl.Nat             `ic:"errors" json:"errors"`
	LastTxTime             uint64              `ic:"lastTxTime" json:"lastTxTime"`
	LastIndexedTx          idl.Nat             `ic:"last_indexed_tx" json:"last_indexed_tx"`
	Pending                idl.Nat             `ic:"pending" json:"pending"`
	ReaderInstructionsCost uint64              `ic:"reader_instructions_cost" json:"reader_instructions_cost"`
	SenderInstructionsCost uint64              `ic:"sender_instructions_cost" json:"sender_instructions_cost"`
}

type GetTransactionsResult struct {
	ArchivedBlocks []ArchivedTransactionResponse `ic:"archived_blocks" json:"archived_blocks"`
	Blocks         []struct {
		Block *Value  `ic:"block,omitempty" json:"block,omitempty"`
		Id    idl.Nat `ic:"id" json:"id"`
	} `ic:"blocks" json:"blocks"`
	LogLength idl.Nat `ic:"log_length" json:"log_length"`
}

type GetTransactionsFn = idl.Function

type GetNodeResponse struct {
	Active  bool `ic:"active" json:"active"`
	Billing struct {
		Account        Account               `ic:"account" json:"account"`
		BillingOption  idl.Nat               `ic:"billing_option" json:"billing_option"`
		CostPerDay     idl.Nat               `ic:"cost_per_day" json:"cost_per_day"`
		CurrentBalance idl.Nat               `ic:"current_balance" json:"current_balance"`
		Expires        *uint64               `ic:"expires,omitempty" json:"expires,omitempty"`
		Frozen         bool                  `ic:"frozen" json:"frozen"`
		TransactionFee BillingTransactionFee `ic:"transaction_fee" json:"transaction_fee"`
	} `ic:"billing" json:"billing"`
	Controllers  []Controller              `ic:"controllers" json:"controllers"`
	Created      uint64                    `ic:"created" json:"created"`
	Custom       *Shared                   `ic:"custom,omitempty" json:"custom,omitempty"`
	Destinations []DestinationEndpointResp `ic:"destinations" json:"destinations"`
	Extractors   []LocalNodeId             `ic:"extractors" json:"extractors"`
	Id           LocalNodeId               `ic:"id" json:"id"`
	Modified     uint64                    `ic:"modified" json:"modified"`
	Refund       Account                   `ic:"refund" json:"refund"`
	Sources      []SourceEndpointResp      `ic:"sources" json:"sources"`
}

type GetNode struct {
	Endpoint *Endpoint    `ic:"endpoint,variant" json:"endpoint,omitempty"`
	Id       *LocalNodeId `ic:"id,variant" json:"id,omitempty"`
}

type GetControllerNodesRequest struct {
	Id     Controller  `ic:"id" json:"id"`
	Length uint32      `ic:"length" json:"length"`
	Start  LocalNodeId `ic:"start" json:"start"`
}

type GetBlocksResult struct {
	ArchivedBlocks []ArchivedTransactionResponse `ic:"archived_blocks" json:"archived_blocks"`
	Blocks         []struct {
		Block *Value  `ic:"block,omitempty" json:"block,omitempty"`
		Id    idl.Nat `ic:"id" json:"id"`
	} `ic:"blocks" json:"blocks"`
	LogLength idl.Nat `ic:"log_length" json:"log_length"`
}

type GetBlocksArgs = []TransactionRange

type GetArchivesResultItem struct {
	CanisterId principal.Principal `ic:"canister_id" json:"canister_id"`
	End        idl.Nat             `ic:"end" json:"end"`
	Start      idl.Nat             `ic:"start" json:"start"`
}

type GetArchivesResult = []GetArchivesResultItem

type GetArchivesArgs struct {
	From *principal.Principal `ic:"from,omitempty" json:"from,omitempty"`
}

type Flow struct {
	Add    *idl.Null `ic:"add,variant" json:"add,omitempty"`
	Remove *idl.Null `ic:"remove,variant" json:"remove,omitempty"`
}

type EndpointsDescription = []struct {
	Field0 LedgerIdx   `ic:"0,tuple" json:"0,tuple"`
	Field1 LedgerLabel `ic:"1,tuple" json:"1,tuple"`
}

type EndpointOther struct {
	Account  []byte `ic:"account" json:"account"`
	Ledger   []byte `ic:"ledger" json:"ledger"`
	Platform uint64 `ic:"platform" json:"platform"`
}

type EndpointOptOther struct {
	Account  *[]byte `ic:"account,omitempty" json:"account,omitempty"`
	Ledger   []byte  `ic:"ledger" json:"ledger"`
	Platform uint64  `ic:"platform" json:"platform"`
}

type EndpointOptIC struct {
	Account *Account            `ic:"account,omitempty" json:"account,omitempty"`
	Ledger  principal.Principal `ic:"ledger" json:"ledger"`
}

type EndpointOpt struct {
	Ic    *EndpointOptIC    `ic:"ic,variant" json:"ic,omitempty"`
	Other *EndpointOptOther `ic:"other,variant" json:"other,omitempty"`
}

type EndpointIdx = uint8

type EndpointIC struct {
	Account Account             `ic:"account" json:"account"`
	Ledger  principal.Principal `ic:"ledger" json:"ledger"`
}

type Endpoint struct {
	Ic    *EndpointIC    `ic:"ic,variant" json:"ic,omitempty"`
	Other *EndpointOther `ic:"other,variant" json:"other,omitempty"`
}

type DestinationEndpointResp struct {
	Endpoint EndpointOpt `ic:"endpoint" json:"endpoint"`
	Name     string      `ic:"name" json:"name"`
}

type DepthRequest struct {
	Level Level  `ic:"level" json:"level"`
	Limit uint32 `ic:"limit" json:"limit"`
}

type DeletePoolResponse struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type DeletePoolRequest struct {
	Base  principal.Principal `ic:"base" json:"base"`
	Quote principal.Principal `ic:"quote" json:"quote"`
}

type DeleteNodeResp struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type DataSource = principal.Principal

type DataCertificate struct {
	Certificate []byte `ic:"certificate" json:"certificate"`
	HashTree    []byte `ic:"hash_tree" json:"hash_tree"`
}

type CreateRequest8 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		Description string `ic:"description" json:"description"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest7 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		IntervalSec NumVariant `ic:"interval_sec" json:"interval_sec"`
		MaxAmount   NumVariant `ic:"max_amount" json:"max_amount"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest6 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		AmountA          NumVariant `ic:"amount_a" json:"amount_a"`
		AmountB          NumVariant `ic:"amount_b" json:"amount_b"`
		SwitchChance     uint64     `ic:"switch_chance" json:"switch_chance"`
		SwitchInterval   NumVariant `ic:"switch_interval" json:"switch_interval"`
		ThrottleInterval NumVariant `ic:"throttle_interval" json:"throttle_interval"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest5 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		Split []idl.Nat `ic:"split" json:"split"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest4 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		Flow  Flow  `ic:"flow" json:"flow"`
		Range Range `ic:"range" json:"range"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest3 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		BuyForAmount       idl.Nat  `ic:"buy_for_amount" json:"buy_for_amount"`
		BuyIntervalSeconds uint64   `ic:"buy_interval_seconds" json:"buy_interval_seconds"`
		MaxImpact          float64  `ic:"max_impact" json:"max_impact"`
		MaxRate            *float64 `ic:"max_rate,omitempty" json:"max_rate,omitempty"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest2 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		PriceLedgerId            principal.Principal `ic:"price_ledger_id" json:"price_ledger_id"`
		RebalanceIntervalSeconds uint64              `ic:"rebalance_interval_seconds" json:"rebalance_interval_seconds"`
		RemoveAmountUsd          idl.Nat             `ic:"remove_amount_usd" json:"remove_amount_usd"`
		RemoveIntervalSeconds    uint64              `ic:"remove_interval_seconds" json:"remove_interval_seconds"`
		SwapAmountUsd            idl.Nat             `ic:"swap_amount_usd" json:"swap_amount_usd"`
		ThresholdPercent         float64             `ic:"threshold_percent" json:"threshold_percent"`
		TokenRatios              []idl.Nat           `ic:"token_ratios" json:"token_ratios"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest1 struct {
	Init struct {
	} `ic:"init" json:"init"`
	Variables struct {
		IntervalSeconds uint64  `ic:"interval_seconds" json:"interval_seconds"`
		Mode            Mode    `ic:"mode" json:"mode"`
		RangePercent    float64 `ic:"range_percent" json:"range_percent"`
		RemovePercent   float64 `ic:"remove_percent" json:"remove_percent"`
	} `ic:"variables" json:"variables"`
}

type CreateRequest struct {
	AutoLiquidity     *CreateRequest1 `ic:"auto_liquidity,variant" json:"auto_liquidity,omitempty"`
	Balancer          *CreateRequest2 `ic:"balancer,variant" json:"balancer,omitempty"`
	Exchange          *CreateRequest3 `ic:"exchange,variant" json:"exchange,omitempty"`
	ExchangeLiquidity *CreateRequest4 `ic:"exchange_liquidity,variant" json:"exchange_liquidity,omitempty"`
	Split             *CreateRequest5 `ic:"split,variant" json:"split,omitempty"`
	Switcher          *CreateRequest6 `ic:"switcher,variant" json:"switcher,omitempty"`
	Throttle          *CreateRequest7 `ic:"throttle,variant" json:"throttle,omitempty"`
	Vault             *CreateRequest8 `ic:"vault,variant" json:"vault,omitempty"`
}

type CreateNodeResponse struct {
	Err *string          `ic:"err,variant" json:"err,omitempty"`
	Ok  *GetNodeResponse `ic:"ok,variant" json:"ok,omitempty"`
}

type CreateNodeRequest struct {
	Field0 CommonCreateRequest `ic:"0,tuple" json:"0,tuple"`
	Field1 CreateRequest       `ic:"1,tuple" json:"1,tuple"`
}

type Controller struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *[]byte             `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type CommonModifyRequest struct {
	Active       *bool            `ic:"active,omitempty" json:"active,omitempty"`
	Controllers  *[]Controller    `ic:"controllers,omitempty" json:"controllers,omitempty"`
	Destinations *[]*InputAddress `ic:"destinations,omitempty" json:"destinations,omitempty"`
	Extractors   *[]LocalNodeId   `ic:"extractors,omitempty" json:"extractors,omitempty"`
	Refund       *Account         `ic:"refund,omitempty" json:"refund,omitempty"`
	Sources      *[]*InputAddress `ic:"sources,omitempty" json:"sources,omitempty"`
}

type CommonCreateRequest struct {
	Affiliate            *Account          `ic:"affiliate,omitempty" json:"affiliate,omitempty"`
	BillingOption        idl.Nat           `ic:"billing_option" json:"billing_option"`
	Controllers          []Controller      `ic:"controllers" json:"controllers"`
	Destinations         []*InputAddress   `ic:"destinations" json:"destinations"`
	Extractors           []LocalNodeId     `ic:"extractors" json:"extractors"`
	InitialBillingAmount *idl.Nat          `ic:"initial_billing_amount,omitempty" json:"initial_billing_amount,omitempty"`
	Ledgers              []SupportedLedger `ic:"ledgers" json:"ledgers"`
	Refund               Account           `ic:"refund" json:"refund"`
	Sources              []*InputAddress   `ic:"sources" json:"sources"`
	TempId               uint32            `ic:"temp_id" json:"temp_id"`
	Temporary            bool              `ic:"temporary" json:"temporary"`
}

type CommandResponse struct {
	CreateNode *CreateNodeResponse `ic:"create_node,variant" json:"create_node,omitempty"`
	DeleteNode *DeleteNodeResp     `ic:"delete_node,variant" json:"delete_node,omitempty"`
	ModifyNode *ModifyNodeResponse `ic:"modify_node,variant" json:"modify_node,omitempty"`
	Transfer   *TransferResponse   `ic:"transfer,variant" json:"transfer,omitempty"`
}

type Command struct {
	CreateNode *CreateNodeRequest `ic:"create_node,variant" json:"create_node,omitempty"`
	DeleteNode *LocalNodeId       `ic:"delete_node,variant" json:"delete_node,omitempty"`
	ModifyNode *ModifyNodeRequest `ic:"modify_node,variant" json:"modify_node,omitempty"`
	Transfer   *TransferRequest   `ic:"transfer,variant" json:"transfer,omitempty"`
}

type ChronoRecord struct {
	Account *C100Account `ic:"account,variant" json:"account,omitempty"`
	Dex     *C200Dex     `ic:"dex,variant" json:"dex,omitempty"`
}

type C200Dex struct {
	LiquidityAdd    *LiquidityAdd    `ic:"liquidityAdd,variant" json:"liquidityAdd,omitempty"`
	LiquidityRemove *LiquidityRemove `ic:"liquidityRemove,variant" json:"liquidityRemove,omitempty"`
	Swap            *Swap            `ic:"swap,variant" json:"swap,omitempty"`
}

type C100Account struct {
	Received *Received `ic:"received,variant" json:"received,omitempty"`
	Sent     *Sent     `ic:"sent,variant" json:"sent,omitempty"`
}

type BlockType struct {
	BlockType string `ic:"block_type" json:"block_type"`
	Url       string `ic:"url" json:"url"`
}

type BillingTransactionFee struct {
	FlatFeeMultiplier           *idl.Nat  `ic:"flat_fee_multiplier,variant" json:"flat_fee_multiplier,omitempty"`
	None                        *idl.Null `ic:"none,variant" json:"none,omitempty"`
	TransactionPercentageFeeE8s *idl.Nat  `ic:"transaction_percentage_fee_e8s,variant" json:"transaction_percentage_fee_e8s,omitempty"`
}

type BillingPylon struct {
	FreezingThresholdDays idl.Nat             `ic:"freezing_threshold_days" json:"freezing_threshold_days"`
	Ledger                principal.Principal `ic:"ledger" json:"ledger"`
	MinCreateBalance      idl.Nat             `ic:"min_create_balance" json:"min_create_balance"`
	OperationCost         idl.Nat             `ic:"operation_cost" json:"operation_cost"`
	PlatformAccount       Account             `ic:"platform_account" json:"platform_account"`
	PylonAccount          Account             `ic:"pylon_account" json:"pylon_account"`
	Split                 BillingFeeSplit     `ic:"split" json:"split"`
}

type BillingFeeSplit struct {
	Affiliate idl.Nat `ic:"affiliate" json:"affiliate"`
	Author    idl.Nat `ic:"author" json:"author"`
	Platform  idl.Nat `ic:"platform" json:"platform"`
	Pylon     idl.Nat `ic:"pylon" json:"pylon"`
}

type Billing struct {
	CostPerDay     idl.Nat               `ic:"cost_per_day" json:"cost_per_day"`
	TransactionFee BillingTransactionFee `ic:"transaction_fee" json:"transaction_fee"`
}

type BatchCommandResponse struct {
	Err *CommandError `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		Commands []CommandResponse `ic:"commands" json:"commands"`
		Id       *idl.Nat          `ic:"id,omitempty" json:"id,omitempty"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type CommandError struct {
	CallerNotController *idl.Null `ic:"caller_not_controller,variant" json:"caller_not_controller,omitempty"`
	Duplicate           *idl.Nat  `ic:"duplicate,variant" json:"duplicate,omitempty"`
	Expired             *idl.Null `ic:"expired,variant" json:"expired,omitempty"`
	InvalidSignature    *idl.Null `ic:"invalid_signature,variant" json:"invalid_signature,omitempty"`
	Other               *string   `ic:"other,variant" json:"other,omitempty"`
}

func (e CommandError) Decode() error {
	switch {
	case e.CallerNotController != nil:
		return fmt.Errorf("caller is not a controller")
	case e.Duplicate != nil:
		return fmt.Errorf("duplicate request (id: %v)", e.Duplicate)
	case e.Expired != nil:
		return fmt.Errorf("request expired")
	case e.InvalidSignature != nil:
		return fmt.Errorf("invalid signature")
	case e.Other != nil:
		return fmt.Errorf("other error: %s", *e.Other)
	default:
		return fmt.Errorf("unknown error")
	}
}

type BatchCommandRequest struct {
	Commands   []Command  `ic:"commands" json:"commands"`
	Controller Controller `ic:"controller" json:"controller"`
	ExpireAt   *uint64    `ic:"expire_at,omitempty" json:"expire_at,omitempty"`
	RequestId  *uint32    `ic:"request_id,omitempty" json:"request_id,omitempty"`
	Signature  *[]byte    `ic:"signature,omitempty" json:"signature,omitempty"`
}

type ArchivedTransactionResponse struct {
	Args     []TransactionRange `ic:"args" json:"args"`
	Callback GetTransactionsFn  `ic:"callback" json:"callback"`
}

type Amount = idl.Nat

type AccountsResponse = []AccountEndpoint

type AccountsRequest struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *[]byte             `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type AccountMixed struct {
	Icp  *[]byte  `ic:"icp,variant" json:"icp,omitempty"`
	Icrc *Account `ic:"icrc,variant" json:"icrc,omitempty"`
}

type AccountEndpoint struct {
	Balance  idl.Nat  `ic:"balance" json:"balance"`
	Endpoint Endpoint `ic:"endpoint" json:"endpoint"`
}

type Account struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *[]byte             `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type API interface {
	Agent() *icp.Agent
	DexQuote(req QuoteRequest) (*QuoteResponse, error)
	DexSwap(req SwapRequest) (*SwapResponse, error)
	GetPendingTransactions() (*[]PendingTransactions, error)
	Icrc55Command(req BatchCommandRequest) (*BatchCommandResponse, error)
}

// api is a client for the "ntn" canister.
type api struct {
	agent      *icp.Agent
	CanisterId principal.Principal
}

// NewAPI creates a new agent for the "ntn" canister.
func NewAPI(canisterId icp.Principal, a *icp.Agent) (*api, error) {
	return &api{
		agent:      a,
		CanisterId: canisterId.Raw(),
	}, nil
}

func (a *api) Agent() *icp.Agent {
	return a.agent
}

// AddSupportedLedger calls the "add_supported_ledger" method on the "ntn" canister.
func (a api) AddSupportedLedger(id principal.Principal, ltype struct {
	Icp  *idl.Null `ic:"icp,variant" json:"icp,omitempty"`
	Icrc *idl.Null `ic:"icrc,variant" json:"icrc,omitempty"`
}) error {
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"add_supported_ledger",
		[]any{id, ltype},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// AdminRecoverTokens calls the "admin_recover_tokens" method on the "ntn" canister.
func (a api) AdminRecoverTokens(arg0 struct {
	Account string              `ic:"account" json:"account"`
	Ledger  principal.Principal `ic:"ledger" json:"ledger"`
	SendTo  string              `ic:"send_to" json:"send_to"`
}) (*Result, error) {
	var r0 Result
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"admin_recover_tokens",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AdminRecoverUnregisteredIcp calls the "admin_recover_unregistered_icp" method on the "ntn" canister.
func (a api) AdminRecoverUnregisteredIcp(arg0 struct {
	Account string `ic:"account" json:"account"`
	SendTo  string `ic:"send_to" json:"send_to"`
}) (*Result, error) {
	var r0 Result
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"admin_recover_unregistered_icp",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// ChronoRecords calls the "chrono_records" method on the "ntn" canister.
func (a api) ChronoRecords() (**ChronoRecord, error) {
	var r0 *ChronoRecord
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"chrono_records",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// ClearPendingTransactions calls the "clear_pending_transactions" method on the "ntn" canister.
func (a api) ClearPendingTransactions() error {
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"clear_pending_transactions",
		[]any{},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// DexOhlcv calls the "dex_ohlcv" method on the "ntn" canister.
func (a api) DexOhlcv(req OHLCVRequest) (*OHLCVResponse, error) {
	var r0 OHLCVResponse
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"dex_ohlcv",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DexPoolCreate calls the "dex_pool_create" method on the "ntn" canister.
func (a api) DexPoolCreate(req PoolRequest) (*PoolResponse, error) {
	var r0 PoolResponse
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"dex_pool_create",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DexPoolDelete calls the "dex_pool_delete" method on the "ntn" canister.
func (a api) DexPoolDelete(req DeletePoolRequest) (*DeletePoolResponse, error) {
	var r0 DeletePoolResponse
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"dex_pool_delete",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DexQuote calls the "dex_quote" method on the "ntn" canister.
func (a api) DexQuote(req QuoteRequest) (*QuoteResponse, error) {
	var r0 QuoteResponse
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"dex_quote",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DexSwap calls the "dex_swap" method on the "ntn" canister.
func (a api) DexSwap(req SwapRequest) (*SwapResponse, error) {
	var r0 SwapResponse
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"dex_swap",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetLedgerErrors calls the "get_ledger_errors" method on the "ntn" canister.
func (a api) GetLedgerErrors() (*[][]string, error) {
	var r0 [][]string
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"get_ledger_errors",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetLedgersInfo calls the "get_ledgers_info" method on the "ntn" canister.
func (a api) GetLedgersInfo() (*[]LedgerInfo1, error) {
	var r0 []LedgerInfo1
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"get_ledgers_info",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetPendingTransactions calls the "get_pending_transactions" method on the "ntn" canister.
func (a api) GetPendingTransactions() (*[]PendingTransactions, error) {
	var r0 []PendingTransactions
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"get_pending_transactions",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetArchives calls the "icrc3_get_archives" method on the "ntn" canister.
func (a api) Icrc3GetArchives(args GetArchivesArgs) (*GetArchivesResult, error) {
	var r0 GetArchivesResult
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc3_get_archives",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetBlocks calls the "icrc3_get_blocks" method on the "ntn" canister.
func (a api) Icrc3GetBlocks(args GetBlocksArgs) (*GetBlocksResult, error) {
	var r0 GetBlocksResult
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc3_get_blocks",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetTipCertificate calls the "icrc3_get_tip_certificate" method on the "ntn" canister.
func (a api) Icrc3GetTipCertificate() (**DataCertificate, error) {
	var r0 *DataCertificate
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc3_get_tip_certificate",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3SupportedBlockTypes calls the "icrc3_supported_block_types" method on the "ntn" canister.
func (a api) Icrc3SupportedBlockTypes() (*[]BlockType, error) {
	var r0 []BlockType
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc3_supported_block_types",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc45GetPairs calls the "icrc45_get_pairs" method on the "ntn" canister.
func (a api) Icrc45GetPairs(req PairRequest) (*PairResponse, error) {
	var r0 PairResponse
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc45_get_pairs",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc45ListPairs calls the "icrc45_list_pairs" method on the "ntn" canister.
func (a api) Icrc45ListPairs() (*ListPairsResponse, error) {
	var r0 ListPairsResponse
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc45_list_pairs",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55AccountRegister calls the "icrc55_account_register" method on the "ntn" canister.
func (a api) Icrc55AccountRegister(acc Account) error {
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"icrc55_account_register",
		[]any{acc},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// Icrc55Accounts calls the "icrc55_accounts" method on the "ntn" canister.
func (a api) Icrc55Accounts(req AccountsRequest) (*AccountsResponse, error) {
	var r0 AccountsResponse
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_accounts",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55Command calls the "icrc55_command" method on the "ntn" canister.
func (a api) Icrc55Command(req BatchCommandRequest) (*BatchCommandResponse, error) {
	var r0 BatchCommandResponse
	if err := a.agent.Raw().Call(
		a.CanisterId,
		"icrc55_command",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55CommandValidate calls the "icrc55_command_validate" method on the "ntn" canister.
func (a api) Icrc55CommandValidate(req BatchCommandRequest) (*ValidationResult, error) {
	var r0 ValidationResult
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_command_validate",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55GetControllerNodes calls the "icrc55_get_controller_nodes" method on the "ntn" canister.
func (a api) Icrc55GetControllerNodes(req GetControllerNodesRequest) (*[]NodeShared, error) {
	var r0 []NodeShared
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_get_controller_nodes",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55GetDefaults calls the "icrc55_get_defaults" method on the "ntn" canister.
func (a api) Icrc55GetDefaults(id string) (*CreateRequest, error) {
	var r0 CreateRequest
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_get_defaults",
		[]any{id},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55GetNodes calls the "icrc55_get_nodes" method on the "ntn" canister.
func (a api) Icrc55GetNodes(req []GetNode) (*[]*NodeShared, error) {
	var r0 []*NodeShared
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_get_nodes",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc55GetPylonMeta calls the "icrc55_get_pylon_meta" method on the "ntn" canister.
func (a api) Icrc55GetPylonMeta() (*PylonMetaResp, error) {
	var r0 PylonMetaResp
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"icrc55_get_pylon_meta",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// TopAccounts calls the "top_accounts" method on the "ntn" canister.
func (a api) TopAccounts(ledger principal.Principal) (*[]struct {
	Field0 []byte  `ic:"0,tuple" json:"0,tuple"`
	Field1 idl.Nat `ic:"1,tuple" json:"1,tuple"`
}, error) {
	var r0 []struct {
		Field0 []byte  `ic:"0,tuple" json:"0,tuple"`
		Field1 idl.Nat `ic:"1,tuple" json:"1,tuple"`
	}
	if err := a.agent.Raw().Query(
		a.CanisterId,
		"top_accounts",
		[]any{ledger},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}
