// Package icpswap_pair provides a client for the "icpswap_pair" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package icpswap_pair

import (
	"github.com/aviate-labs/agent-go"
	"github.com/aviate-labs/agent-go/candid/idl"
	"github.com/aviate-labs/agent-go/principal"
	"github.com/niccolofant/ic-arb/icp"
)

type WithdrawToSubaccountArgs struct {
	Amount     idl.Nat `ic:"amount" json:"amount"`
	Fee        idl.Nat `ic:"fee" json:"fee"`
	Subaccount []byte  `ic:"subaccount" json:"subaccount"`
	Token      string  `ic:"token" json:"token"`
}

type WithdrawStatus struct {
	Completed       *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created         *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	CreditCompleted *idl.Null `ic:"CreditCompleted,variant" json:"CreditCompleted,omitempty"`
	Failed          *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type WithdrawInfo struct {
	Err      *Error1        `ic:"err,omitempty" json:"err,omitempty"`
	Status   WithdrawStatus `ic:"status" json:"status"`
	Transfer Transfer       `ic:"transfer" json:"transfer"`
}

type WithdrawArgs struct {
	Amount idl.Nat `ic:"amount" json:"amount"`
	Fee    idl.Nat `ic:"fee" json:"fee"`
	Token  string  `ic:"token" json:"token"`
}

type UserPositionInfoWithTokenAmount struct {
	FeeGrowthInside0LastX128 idl.Nat `ic:"feeGrowthInside0LastX128" json:"feeGrowthInside0LastX128"`
	FeeGrowthInside1LastX128 idl.Nat `ic:"feeGrowthInside1LastX128" json:"feeGrowthInside1LastX128"`
	Id                       idl.Nat `ic:"id" json:"id"`
	Liquidity                idl.Nat `ic:"liquidity" json:"liquidity"`
	TickLower                idl.Int `ic:"tickLower" json:"tickLower"`
	TickUpper                idl.Int `ic:"tickUpper" json:"tickUpper"`
	Token0Amount             idl.Nat `ic:"token0Amount" json:"token0Amount"`
	Token1Amount             idl.Nat `ic:"token1Amount" json:"token1Amount"`
	TokensOwed0              idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
	TokensOwed1              idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
}

type UserPositionInfoWithId struct {
	FeeGrowthInside0LastX128 idl.Nat `ic:"feeGrowthInside0LastX128" json:"feeGrowthInside0LastX128"`
	FeeGrowthInside1LastX128 idl.Nat `ic:"feeGrowthInside1LastX128" json:"feeGrowthInside1LastX128"`
	Id                       idl.Nat `ic:"id" json:"id"`
	Liquidity                idl.Nat `ic:"liquidity" json:"liquidity"`
	TickLower                idl.Int `ic:"tickLower" json:"tickLower"`
	TickUpper                idl.Int `ic:"tickUpper" json:"tickUpper"`
	TokensOwed0              idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
	TokensOwed1              idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
}

type UserPositionInfo struct {
	FeeGrowthInside0LastX128 idl.Nat `ic:"feeGrowthInside0LastX128" json:"feeGrowthInside0LastX128"`
	FeeGrowthInside1LastX128 idl.Nat `ic:"feeGrowthInside1LastX128" json:"feeGrowthInside1LastX128"`
	Liquidity                idl.Nat `ic:"liquidity" json:"liquidity"`
	TickLower                idl.Int `ic:"tickLower" json:"tickLower"`
	TickUpper                idl.Int `ic:"tickUpper" json:"tickUpper"`
	TokensOwed0              idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
	TokensOwed1              idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
}

type TransferPositionStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type TransferPositionInfo struct {
	Err          *Error1                `ic:"err,omitempty" json:"err,omitempty"`
	From         Account                `ic:"from" json:"from"`
	PositionId   idl.Nat                `ic:"positionId" json:"positionId"`
	Status       TransferPositionStatus `ic:"status" json:"status"`
	To           Account                `ic:"to" json:"to"`
	Token0Amount idl.Nat                `ic:"token0Amount" json:"token0Amount"`
	Token1Amount idl.Nat                `ic:"token1Amount" json:"token1Amount"`
}

type Transfer struct {
	Amount   idl.Nat             `ic:"amount" json:"amount"`
	Fee      idl.Nat             `ic:"fee" json:"fee"`
	From     Account             `ic:"from" json:"from"`
	Index    idl.Nat             `ic:"index" json:"index"`
	Memo     *[]byte             `ic:"memo,omitempty" json:"memo,omitempty"`
	Standard string              `ic:"standard" json:"standard"`
	To       Account             `ic:"to" json:"to"`
	Token    principal.Principal `ic:"token" json:"token"`
}

type Transaction1 struct {
	Action     Action              `ic:"action" json:"action"`
	CanisterId principal.Principal `ic:"canisterId" json:"canisterId"`
	Id         idl.Nat             `ic:"id" json:"id"`
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Timestamp  Time                `ic:"timestamp" json:"timestamp"`
}

type Transaction struct {
	Action     Action              `ic:"action" json:"action"`
	CanisterId principal.Principal `ic:"canisterId" json:"canisterId"`
	Id         idl.Nat             `ic:"id" json:"id"`
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Timestamp  Time                `ic:"timestamp" json:"timestamp"`
}

type Token1 struct {
	Address  principal.Principal `ic:"address" json:"address"`
	Standard string              `ic:"standard" json:"standard"`
}

type Token struct {
	Address  string `ic:"address" json:"address"`
	Standard string `ic:"standard" json:"standard"`
}

type Time = idl.Int

type TickLiquidityInfo struct {
	LiquidityGross idl.Nat `ic:"liquidityGross" json:"liquidityGross"`
	LiquidityNet   idl.Int `ic:"liquidityNet" json:"liquidityNet"`
	Price0         idl.Nat `ic:"price0" json:"price0"`
	Price0Decimal  idl.Nat `ic:"price0Decimal" json:"price0Decimal"`
	Price1         idl.Nat `ic:"price1" json:"price1"`
	Price1Decimal  idl.Nat `ic:"price1Decimal" json:"price1Decimal"`
	TickIndex      idl.Int `ic:"tickIndex" json:"tickIndex"`
}

type TickInfoWithId struct {
	FeeGrowthOutside0X128          idl.Nat `ic:"feeGrowthOutside0X128" json:"feeGrowthOutside0X128"`
	FeeGrowthOutside1X128          idl.Nat `ic:"feeGrowthOutside1X128" json:"feeGrowthOutside1X128"`
	Id                             string  `ic:"id" json:"id"`
	Initialized                    bool    `ic:"initialized" json:"initialized"`
	LiquidityGross                 idl.Nat `ic:"liquidityGross" json:"liquidityGross"`
	LiquidityNet                   idl.Int `ic:"liquidityNet" json:"liquidityNet"`
	SecondsOutside                 idl.Nat `ic:"secondsOutside" json:"secondsOutside"`
	SecondsPerLiquidityOutsideX128 idl.Nat `ic:"secondsPerLiquidityOutsideX128" json:"secondsPerLiquidityOutsideX128"`
	TickCumulativeOutside          idl.Int `ic:"tickCumulativeOutside" json:"tickCumulativeOutside"`
}

type SwapStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type SwapRecordInfo struct {
	CurrentLiquidity    idl.Nat      `ic:"currentLiquidity" json:"currentLiquidity"`
	CurrentSqrtPriceX96 idl.Nat      `ic:"currentSqrtPriceX96" json:"currentSqrtPriceX96"`
	CurrentTick         idl.Int      `ic:"currentTick" json:"currentTick"`
	PoolFee             idl.Nat      `ic:"poolFee" json:"poolFee"`
	TxInfo              Transaction1 `ic:"txInfo" json:"txInfo"`
}

type SwapInfo struct {
	AmountIn     Amount     `ic:"amountIn" json:"amountIn"`
	AmountInFee  idl.Nat    `ic:"amountInFee" json:"amountInFee"`
	AmountOut    idl.Nat    `ic:"amountOut" json:"amountOut"`
	AmountOutFee idl.Nat    `ic:"amountOutFee" json:"amountOutFee"`
	Err          *Error1    `ic:"err,omitempty" json:"err,omitempty"`
	Status       SwapStatus `ic:"status" json:"status"`
	TokenIn      Token1     `ic:"tokenIn" json:"tokenIn"`
	TokenOut     Token1     `ic:"tokenOut" json:"tokenOut"`
}

type SwapArgs struct {
	AmountIn         string `ic:"amountIn" json:"amountIn"`
	AmountOutMinimum string `ic:"amountOutMinimum" json:"amountOutMinimum"`
	ZeroForOne       bool   `ic:"zeroForOne" json:"zeroForOne"`
}

type Result9 struct {
	Err *Error                    `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]UserPositionInfoWithId `ic:"ok,variant" json:"ok,omitempty"`
}

type Result8 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		Balance0 idl.Nat `ic:"balance0" json:"balance0"`
		Balance1 idl.Nat `ic:"balance1" json:"balance1"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result7 struct {
	Err *Error        `ic:"err,variant" json:"err,omitempty"`
	Ok  *PoolMetadata `ic:"ok,variant" json:"ok,omitempty"`
}

type Result6 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		TokensOwed0 idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
		TokensOwed1 idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result5 struct {
	Err *idl.Null `ic:"err,variant" json:"err,omitempty"`
	Ok  *bool     `ic:"ok,variant" json:"ok,omitempty"`
}

type Result4 struct {
	Err *Error    `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type Result32 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page5 `ic:"ok,variant" json:"ok,omitempty"`
}

type Result31 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		TokenIncome []struct {
			Field0 idl.Nat `ic:"0,tuple" json:"0,tuple"`
			Field1 struct {
				TokensOwed0 idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
				TokensOwed1 idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
			} `ic:"1,tuple" json:"1,tuple"`
		} `ic:"tokenIncome" json:"tokenIncome"`
		TotalTokensOwed0 idl.Nat `ic:"totalTokensOwed0" json:"totalTokensOwed0"`
		TotalTokensOwed1 idl.Nat `ic:"totalTokensOwed1" json:"totalTokensOwed1"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result30 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		Amount0 idl.Nat `ic:"amount0" json:"amount0"`
		Amount1 idl.Nat `ic:"amount1" json:"amount1"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result3 struct {
	Err *Error   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Int `ic:"ok,variant" json:"ok,omitempty"`
}

type Result29 struct {
	Err *Error     `ic:"err,variant" json:"err,omitempty"`
	Ok  *CycleInfo `ic:"ok,variant" json:"ok,omitempty"`
}

type Result28 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		FeeGrowthGlobal0X128 idl.Nat `ic:"feeGrowthGlobal0X128" json:"feeGrowthGlobal0X128"`
		FeeGrowthGlobal1X128 idl.Nat `ic:"feeGrowthGlobal1X128" json:"feeGrowthGlobal1X128"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result27 struct {
	Err *Error        `ic:"err,variant" json:"err,omitempty"`
	Ok  *PoolInitArgs `ic:"ok,variant" json:"ok,omitempty"`
}

type Result26 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]struct {
		Field0 LimitOrderType  `ic:"0,tuple" json:"0,tuple"`
		Field1 LimitOrderKey   `ic:"1,tuple" json:"1,tuple"`
		Field2 LimitOrderValue `ic:"2,tuple" json:"2,tuple"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result25 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		LowerLimitOrders []struct {
			Field0 LimitOrderKey   `ic:"0,tuple" json:"0,tuple"`
			Field1 LimitOrderValue `ic:"1,tuple" json:"1,tuple"`
		} `ic:"lowerLimitOrders" json:"lowerLimitOrders"`
		UpperLimitOrders []struct {
			Field0 LimitOrderKey   `ic:"0,tuple" json:"0,tuple"`
			Field1 LimitOrderValue `ic:"1,tuple" json:"1,tuple"`
		} `ic:"upperLimitOrders" json:"upperLimitOrders"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result24 struct {
	Err *Error        `ic:"err,variant" json:"err,omitempty"`
	Ok  *PositionInfo `ic:"ok,variant" json:"ok,omitempty"`
}

type Result23 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page4 `ic:"ok,variant" json:"ok,omitempty"`
}

type Result22 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]struct {
		TickLimit      idl.Int `ic:"tickLimit" json:"tickLimit"`
		Timestamp      idl.Nat `ic:"timestamp" json:"timestamp"`
		Token0InAmount idl.Nat `ic:"token0InAmount" json:"token0InAmount"`
		Token1InAmount idl.Nat `ic:"token1InAmount" json:"token1InAmount"`
		UserPositionId idl.Nat `ic:"userPositionId" json:"userPositionId"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result21 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		Errors     []PushError      `ic:"errors" json:"errors"`
		InfoCid    string           `ic:"infoCid" json:"infoCid"`
		Records    []SwapRecordInfo `ic:"records" json:"records"`
		RetryCount idl.Nat          `ic:"retryCount" json:"retryCount"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result20 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]struct {
		Field0 idl.Int `ic:"0,tuple" json:"0,tuple"`
		Field1 idl.Nat `ic:"1,tuple" json:"1,tuple"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result2 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *bool  `ic:"ok,variant" json:"ok,omitempty"`
}

type Result19 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page3 `ic:"ok,variant" json:"ok,omitempty"`
}

type Result18 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page2 `ic:"ok,variant" json:"ok,omitempty"`
}

type Result17 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		SwapFee0Repurchase idl.Nat `ic:"swapFee0Repurchase" json:"swapFee0Repurchase"`
		SwapFee1Repurchase idl.Nat `ic:"swapFee1Repurchase" json:"swapFee1Repurchase"`
		SwapFeeReceiver    string  `ic:"swapFeeReceiver" json:"swapFeeReceiver"`
		Token0Amount       idl.Nat `ic:"token0Amount" json:"token0Amount"`
		Token1Amount       idl.Nat `ic:"token1Amount" json:"token1Amount"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result16 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]struct {
		Field0 idl.Nat     `ic:"0,tuple" json:"0,tuple"`
		Field1 Transaction `ic:"1,tuple" json:"1,tuple"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result15 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *struct {
		LowerLimitOrderIds []struct {
			Timestamp      idl.Nat `ic:"timestamp" json:"timestamp"`
			UserPositionId idl.Nat `ic:"userPositionId" json:"userPositionId"`
		} `ic:"lowerLimitOrderIds" json:"lowerLimitOrderIds"`
		UpperLimitOrdersIds []struct {
			Timestamp      idl.Nat `ic:"timestamp" json:"timestamp"`
			UserPositionId idl.Nat `ic:"userPositionId" json:"userPositionId"`
		} `ic:"upperLimitOrdersIds" json:"upperLimitOrdersIds"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result14 struct {
	Err *Error            `ic:"err,variant" json:"err,omitempty"`
	Ok  *UserPositionInfo `ic:"ok,variant" json:"ok,omitempty"`
}

type Result13 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]struct {
		Field0 string    `ic:"0,tuple" json:"0,tuple"`
		Field1 []idl.Nat `ic:"1,tuple" json:"1,tuple"`
	} `ic:"ok,variant" json:"ok,omitempty"`
}

type Result12 struct {
	Err *Error     `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]idl.Nat `ic:"ok,variant" json:"ok,omitempty"`
}

type Result11 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page1 `ic:"ok,variant" json:"ok,omitempty"`
}

type Result10 struct {
	Err *Error `ic:"err,variant" json:"err,omitempty"`
	Ok  *Page  `ic:"ok,variant" json:"ok,omitempty"`
}

type Result1 struct {
	Err *Error  `ic:"err,variant" json:"err,omitempty"`
	Ok  *string `ic:"ok,variant" json:"ok,omitempty"`
}

type Result struct {
	Err *Error   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Nat `ic:"ok,variant" json:"ok,omitempty"`
}

type RemoveLimitOrderStatus struct {
	Completed         *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created           *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed            *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
	LimitOrderDeleted *idl.Null `ic:"LimitOrderDeleted,variant" json:"LimitOrderDeleted,omitempty"`
}

type RemoveLimitOrderInfo struct {
	Err             *Error1                `ic:"err,omitempty" json:"err,omitempty"`
	PositionId      idl.Nat                `ic:"positionId" json:"positionId"`
	Status          RemoveLimitOrderStatus `ic:"status" json:"status"`
	TickLimit       idl.Int                `ic:"tickLimit" json:"tickLimit"`
	Token0          Token1                 `ic:"token0" json:"token0"`
	Token0AmountIn  idl.Nat                `ic:"token0AmountIn" json:"token0AmountIn"`
	Token0AmountOut idl.Nat                `ic:"token0AmountOut" json:"token0AmountOut"`
	Token1          Token1                 `ic:"token1" json:"token1"`
	Token1AmountIn  idl.Nat                `ic:"token1AmountIn" json:"token1AmountIn"`
	Token1AmountOut idl.Nat                `ic:"token1AmountOut" json:"token1AmountOut"`
}

type RefundStatus struct {
	Completed       *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created         *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	CreditCompleted *idl.Null `ic:"CreditCompleted,variant" json:"CreditCompleted,omitempty"`
	Failed          *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type RefundInfo struct {
	Err          *Error1      `ic:"err,omitempty" json:"err,omitempty"`
	RelatedIndex idl.Nat      `ic:"relatedIndex" json:"relatedIndex"`
	Status       RefundStatus `ic:"status" json:"status"`
	Transfer     Transfer     `ic:"transfer" json:"transfer"`
}

type PushError struct {
	Message string  `ic:"message" json:"message"`
	Time    idl.Int `ic:"time" json:"time"`
}

type PositionInfoWithId struct {
	FeeGrowthInside0LastX128 idl.Nat `ic:"feeGrowthInside0LastX128" json:"feeGrowthInside0LastX128"`
	FeeGrowthInside1LastX128 idl.Nat `ic:"feeGrowthInside1LastX128" json:"feeGrowthInside1LastX128"`
	Id                       string  `ic:"id" json:"id"`
	Liquidity                idl.Nat `ic:"liquidity" json:"liquidity"`
	TokensOwed0              idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
	TokensOwed1              idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
}

type PositionInfo struct {
	FeeGrowthInside0LastX128 idl.Nat `ic:"feeGrowthInside0LastX128" json:"feeGrowthInside0LastX128"`
	FeeGrowthInside1LastX128 idl.Nat `ic:"feeGrowthInside1LastX128" json:"feeGrowthInside1LastX128"`
	Liquidity                idl.Nat `ic:"liquidity" json:"liquidity"`
	TokensOwed0              idl.Nat `ic:"tokensOwed0" json:"tokensOwed0"`
	TokensOwed1              idl.Nat `ic:"tokensOwed1" json:"tokensOwed1"`
}

type PoolMetadata struct {
	Fee                 idl.Nat `ic:"fee" json:"fee"`
	Key                 string  `ic:"key" json:"key"`
	Liquidity           idl.Nat `ic:"liquidity" json:"liquidity"`
	MaxLiquidityPerTick idl.Nat `ic:"maxLiquidityPerTick" json:"maxLiquidityPerTick"`
	NextPositionId      idl.Nat `ic:"nextPositionId" json:"nextPositionId"`
	SqrtPriceX96        idl.Nat `ic:"sqrtPriceX96" json:"sqrtPriceX96"`
	Tick                idl.Int `ic:"tick" json:"tick"`
	Token0              Token   `ic:"token0" json:"token0"`
	Token1              Token   `ic:"token1" json:"token1"`
}

type PoolInitArgs struct {
	FeeReceiverCid            principal.Principal `ic:"feeReceiverCid" json:"feeReceiverCid"`
	InfoCid                   principal.Principal `ic:"infoCid" json:"infoCid"`
	PositionIndexCid          principal.Principal `ic:"positionIndexCid" json:"positionIndexCid"`
	Token0                    Token               `ic:"token0" json:"token0"`
	Token1                    Token               `ic:"token1" json:"token1"`
	TrustedCanisterManagerCid principal.Principal `ic:"trustedCanisterManagerCid" json:"trustedCanisterManagerCid"`
}

type Page5 struct {
	Content []struct {
		Field0 principal.Principal `ic:"0,tuple" json:"0,tuple"`
		Field1 AccountBalance      `ic:"1,tuple" json:"1,tuple"`
	} `ic:"content" json:"content"`
	Limit         idl.Nat `ic:"limit" json:"limit"`
	Offset        idl.Nat `ic:"offset" json:"offset"`
	TotalElements idl.Nat `ic:"totalElements" json:"totalElements"`
}

type Page4 struct {
	Content       []PositionInfoWithId `ic:"content" json:"content"`
	Limit         idl.Nat              `ic:"limit" json:"limit"`
	Offset        idl.Nat              `ic:"offset" json:"offset"`
	TotalElements idl.Nat              `ic:"totalElements" json:"totalElements"`
}

type Page3 struct {
	Content       []TickLiquidityInfo `ic:"content" json:"content"`
	Limit         idl.Nat             `ic:"limit" json:"limit"`
	Offset        idl.Nat             `ic:"offset" json:"offset"`
	TotalElements idl.Nat             `ic:"totalElements" json:"totalElements"`
}

type Page2 struct {
	Content       []TickInfoWithId `ic:"content" json:"content"`
	Limit         idl.Nat          `ic:"limit" json:"limit"`
	Offset        idl.Nat          `ic:"offset" json:"offset"`
	TotalElements idl.Nat          `ic:"totalElements" json:"totalElements"`
}

type Page1 struct {
	Content       []UserPositionInfoWithTokenAmount `ic:"content" json:"content"`
	Limit         idl.Nat                           `ic:"limit" json:"limit"`
	Offset        idl.Nat                           `ic:"offset" json:"offset"`
	TotalElements idl.Nat                           `ic:"totalElements" json:"totalElements"`
}

type Page struct {
	Content       []UserPositionInfoWithId `ic:"content" json:"content"`
	Limit         idl.Nat                  `ic:"limit" json:"limit"`
	Offset        idl.Nat                  `ic:"offset" json:"offset"`
	TotalElements idl.Nat                  `ic:"totalElements" json:"totalElements"`
}

type OneStepSwapStatus struct {
	Completed                *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created                  *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	DepositCreditCompleted   *idl.Null `ic:"DepositCreditCompleted,variant" json:"DepositCreditCompleted,omitempty"`
	DepositTransferCompleted *idl.Null `ic:"DepositTransferCompleted,variant" json:"DepositTransferCompleted,omitempty"`
	Failed                   *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
	PreSwapCompleted         *idl.Null `ic:"PreSwapCompleted,variant" json:"PreSwapCompleted,omitempty"`
	SwapCompleted            *idl.Null `ic:"SwapCompleted,variant" json:"SwapCompleted,omitempty"`
	WithdrawCreditCompleted  *idl.Null `ic:"WithdrawCreditCompleted,variant" json:"WithdrawCreditCompleted,omitempty"`
}

type OneStepSwapInfo struct {
	Deposit  DepositInfo       `ic:"deposit" json:"deposit"`
	Err      *Error1           `ic:"err,omitempty" json:"err,omitempty"`
	Status   OneStepSwapStatus `ic:"status" json:"status"`
	Swap     SwapInfo          `ic:"swap" json:"swap"`
	Withdraw WithdrawInfo      `ic:"withdraw" json:"withdraw"`
}

type MintArgs struct {
	Amount0Desired string  `ic:"amount0Desired" json:"amount0Desired"`
	Amount1Desired string  `ic:"amount1Desired" json:"amount1Desired"`
	Fee            idl.Nat `ic:"fee" json:"fee"`
	TickLower      idl.Int `ic:"tickLower" json:"tickLower"`
	TickUpper      idl.Int `ic:"tickUpper" json:"tickUpper"`
	Token0         string  `ic:"token0" json:"token0"`
	Token1         string  `ic:"token1" json:"token1"`
}

type LimitOrderValue struct {
	Owner          principal.Principal `ic:"owner" json:"owner"`
	Token0InAmount idl.Nat             `ic:"token0InAmount" json:"token0InAmount"`
	Token1InAmount idl.Nat             `ic:"token1InAmount" json:"token1InAmount"`
	UserPositionId idl.Nat             `ic:"userPositionId" json:"userPositionId"`
}

type LimitOrderType struct {
	Lower *idl.Null `ic:"Lower,variant" json:"Lower,omitempty"`
	Upper *idl.Null `ic:"Upper,variant" json:"Upper,omitempty"`
}

type LimitOrderKey struct {
	TickLimit idl.Int `ic:"tickLimit" json:"tickLimit"`
	Timestamp idl.Nat `ic:"timestamp" json:"timestamp"`
}

type LimitOrderArgs struct {
	PositionId idl.Nat `ic:"positionId" json:"positionId"`
	TickLimit  idl.Int `ic:"tickLimit" json:"tickLimit"`
}

type Level struct {
	Active   *idl.Null `ic:"Active,variant" json:"Active,omitempty"`
	Inactive *idl.Null `ic:"Inactive,variant" json:"Inactive,omitempty"`
}

type JobInfo struct {
	Interval idl.Nat  `ic:"interval" json:"interval"`
	LastRun  Time     `ic:"lastRun" json:"lastRun"`
	Name     string   `ic:"name" json:"name"`
	TimerId  *idl.Nat `ic:"timerId,omitempty" json:"timerId,omitempty"`
}

type IncreaseLiquidityArgs struct {
	Amount0Desired string  `ic:"amount0Desired" json:"amount0Desired"`
	Amount1Desired string  `ic:"amount1Desired" json:"amount1Desired"`
	PositionId     idl.Nat `ic:"positionId" json:"positionId"`
}

type Icrc28TrustedOriginsResponse struct {
	TrustedOrigins []string `ic:"trusted_origins" json:"trusted_origins"`
}

type Icrc21ErrorInfo struct {
	Description string `ic:"description" json:"description"`
}

type Icrc21Error struct {
	ConsentMessageUnavailable *Icrc21ErrorInfo `ic:"ConsentMessageUnavailable,variant" json:"ConsentMessageUnavailable,omitempty"`
	GenericError              *struct {
		Description string  `ic:"description" json:"description"`
		ErrorCode   idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	InsufficientPayment     *Icrc21ErrorInfo `ic:"InsufficientPayment,variant" json:"InsufficientPayment,omitempty"`
	UnsupportedCanisterCall *Icrc21ErrorInfo `ic:"UnsupportedCanisterCall,variant" json:"UnsupportedCanisterCall,omitempty"`
}

type Icrc21ConsentMessageSpec struct {
	DeviceSpec *struct {
		GenericDisplay *idl.Null `ic:"GenericDisplay,variant" json:"GenericDisplay,omitempty"`
		LineDisplay    *struct {
			CharactersPerLine uint16 `ic:"characters_per_line" json:"characters_per_line"`
			LinesPerPage      uint16 `ic:"lines_per_page" json:"lines_per_page"`
		} `ic:"LineDisplay,variant" json:"LineDisplay,omitempty"`
	} `ic:"device_spec,omitempty" json:"device_spec,omitempty"`
	Metadata Icrc21ConsentMessageMetadata `ic:"metadata" json:"metadata"`
}

type Icrc21ConsentMessageResponse struct {
	Err *Icrc21Error       `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *Icrc21ConsentInfo `ic:"Ok,variant" json:"Ok,omitempty"`
}

type Icrc21ConsentMessageRequest struct {
	Arg             []byte                   `ic:"arg" json:"arg"`
	Method          string                   `ic:"method" json:"method"`
	UserPreferences Icrc21ConsentMessageSpec `ic:"user_preferences" json:"user_preferences"`
}

type Icrc21ConsentMessageMetadata struct {
	Language         string `ic:"language" json:"language"`
	UtcOffsetMinutes *int16 `ic:"utc_offset_minutes,omitempty" json:"utc_offset_minutes,omitempty"`
}

type Icrc21ConsentMessage struct {
	GenericDisplayMessage *string `ic:"GenericDisplayMessage,variant" json:"GenericDisplayMessage,omitempty"`
	LineDisplayMessage    *struct {
		Pages []struct {
			Lines []string `ic:"lines" json:"lines"`
		} `ic:"pages" json:"pages"`
	} `ic:"LineDisplayMessage,variant" json:"LineDisplayMessage,omitempty"`
}

type Icrc21ConsentInfo struct {
	ConsentMessage Icrc21ConsentMessage         `ic:"consent_message" json:"consent_message"`
	Metadata       Icrc21ConsentMessageMetadata `ic:"metadata" json:"metadata"`
}

type GetPositionArgs struct {
	TickLower idl.Int `ic:"tickLower" json:"tickLower"`
	TickUpper idl.Int `ic:"tickUpper" json:"tickUpper"`
}

type ExecuteLimitOrderStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type ExecuteLimitOrderInfo struct {
	Err             *Error1                 `ic:"err,omitempty" json:"err,omitempty"`
	PositionId      idl.Nat                 `ic:"positionId" json:"positionId"`
	Status          ExecuteLimitOrderStatus `ic:"status" json:"status"`
	TickLimit       idl.Int                 `ic:"tickLimit" json:"tickLimit"`
	Token0          Token1                  `ic:"token0" json:"token0"`
	Token0AmountIn  idl.Nat                 `ic:"token0AmountIn" json:"token0AmountIn"`
	Token0AmountOut idl.Nat                 `ic:"token0AmountOut" json:"token0AmountOut"`
	Token1          Token1                  `ic:"token1" json:"token1"`
	Token1AmountIn  idl.Nat                 `ic:"token1AmountIn" json:"token1AmountIn"`
	Token1AmountOut idl.Nat                 `ic:"token1AmountOut" json:"token1AmountOut"`
}

type Error1 = string

type Error struct {
	CommonError       *idl.Null `ic:"CommonError,variant" json:"CommonError,omitempty"`
	InsufficientFunds *idl.Null `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
	InternalError     *string   `ic:"InternalError,variant" json:"InternalError,omitempty"`
	UnsupportedToken  *string   `ic:"UnsupportedToken,variant" json:"UnsupportedToken,omitempty"`
}

type DepositStatus struct {
	Completed         *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created           *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed            *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
	TransferCompleted *idl.Null `ic:"TransferCompleted,variant" json:"TransferCompleted,omitempty"`
}

type DepositInfo struct {
	Err      *Error1       `ic:"err,omitempty" json:"err,omitempty"`
	Status   DepositStatus `ic:"status" json:"status"`
	Transfer Transfer      `ic:"transfer" json:"transfer"`
}

type DepositArgs struct {
	Amount idl.Nat `ic:"amount" json:"amount"`
	Fee    idl.Nat `ic:"fee" json:"fee"`
	Token  string  `ic:"token" json:"token"`
}

type DepositAndSwapArgs struct {
	AmountIn         string  `ic:"amountIn" json:"amountIn"`
	AmountOutMinimum string  `ic:"amountOutMinimum" json:"amountOutMinimum"`
	TokenInFee       idl.Nat `ic:"tokenInFee" json:"tokenInFee"`
	TokenOutFee      idl.Nat `ic:"tokenOutFee" json:"tokenOutFee"`
	ZeroForOne       bool    `ic:"zeroForOne" json:"zeroForOne"`
}

type DepositAndMintArgs struct {
	Amount0        idl.Nat             `ic:"amount0" json:"amount0"`
	Amount0Desired string              `ic:"amount0Desired" json:"amount0Desired"`
	Amount1        idl.Nat             `ic:"amount1" json:"amount1"`
	Amount1Desired string              `ic:"amount1Desired" json:"amount1Desired"`
	Fee0           idl.Nat             `ic:"fee0" json:"fee0"`
	Fee1           idl.Nat             `ic:"fee1" json:"fee1"`
	PositionOwner  principal.Principal `ic:"positionOwner" json:"positionOwner"`
	TickLower      idl.Int             `ic:"tickLower" json:"tickLower"`
	TickUpper      idl.Int             `ic:"tickUpper" json:"tickUpper"`
}

type DecreaseLiquidityStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type DecreaseLiquidityInfo struct {
	Amount0    idl.Nat                 `ic:"amount0" json:"amount0"`
	Amount1    idl.Nat                 `ic:"amount1" json:"amount1"`
	Err        *Error1                 `ic:"err,omitempty" json:"err,omitempty"`
	Liquidity  idl.Nat                 `ic:"liquidity" json:"liquidity"`
	PositionId idl.Nat                 `ic:"positionId" json:"positionId"`
	Status     DecreaseLiquidityStatus `ic:"status" json:"status"`
	Token0     Token1                  `ic:"token0" json:"token0"`
	Token1     Token1                  `ic:"token1" json:"token1"`
}

type DecreaseLiquidityArgs struct {
	Liquidity  string  `ic:"liquidity" json:"liquidity"`
	PositionId idl.Nat `ic:"positionId" json:"positionId"`
}

type CycleInfo struct {
	Available idl.Nat `ic:"available" json:"available"`
	Balance   idl.Nat `ic:"balance" json:"balance"`
}

type ClaimStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type ClaimInfo struct {
	Amount0    idl.Nat     `ic:"amount0" json:"amount0"`
	Amount1    idl.Nat     `ic:"amount1" json:"amount1"`
	Err        *Error1     `ic:"err,omitempty" json:"err,omitempty"`
	PositionId idl.Nat     `ic:"positionId" json:"positionId"`
	Status     ClaimStatus `ic:"status" json:"status"`
	Token0     Token1      `ic:"token0" json:"token0"`
	Token1     Token1      `ic:"token1" json:"token1"`
}

type ClaimArgs struct {
	PositionId idl.Nat `ic:"positionId" json:"positionId"`
}

type Amount = idl.Nat

type AddLiquidityStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type AddLiquidityInfo struct {
	Amount0    idl.Nat            `ic:"amount0" json:"amount0"`
	Amount1    idl.Nat            `ic:"amount1" json:"amount1"`
	Err        *Error1            `ic:"err,omitempty" json:"err,omitempty"`
	Liquidity  idl.Nat            `ic:"liquidity" json:"liquidity"`
	PositionId idl.Nat            `ic:"positionId" json:"positionId"`
	Status     AddLiquidityStatus `ic:"status" json:"status"`
	Token0     Token1             `ic:"token0" json:"token0"`
	Token1     Token1             `ic:"token1" json:"token1"`
}

type AddLimitOrderStatus struct {
	Completed *idl.Null `ic:"Completed,variant" json:"Completed,omitempty"`
	Created   *idl.Null `ic:"Created,variant" json:"Created,omitempty"`
	Failed    *idl.Null `ic:"Failed,variant" json:"Failed,omitempty"`
}

type AddLimitOrderInfo struct {
	Err            *Error1             `ic:"err,omitempty" json:"err,omitempty"`
	PositionId     idl.Nat             `ic:"positionId" json:"positionId"`
	Status         AddLimitOrderStatus `ic:"status" json:"status"`
	TickLimit      idl.Int             `ic:"tickLimit" json:"tickLimit"`
	Token0         Token1              `ic:"token0" json:"token0"`
	Token0AmountIn idl.Nat             `ic:"token0AmountIn" json:"token0AmountIn"`
	Token1         Token1              `ic:"token1" json:"token1"`
	Token1AmountIn idl.Nat             `ic:"token1AmountIn" json:"token1AmountIn"`
}

type Action struct {
	AddLimitOrder     *AddLimitOrderInfo     `ic:"AddLimitOrder,variant" json:"AddLimitOrder,omitempty"`
	AddLiquidity      *AddLiquidityInfo      `ic:"AddLiquidity,variant" json:"AddLiquidity,omitempty"`
	Claim             *ClaimInfo             `ic:"Claim,variant" json:"Claim,omitempty"`
	DecreaseLiquidity *DecreaseLiquidityInfo `ic:"DecreaseLiquidity,variant" json:"DecreaseLiquidity,omitempty"`
	Deposit           *DepositInfo           `ic:"Deposit,variant" json:"Deposit,omitempty"`
	ExecuteLimitOrder *ExecuteLimitOrderInfo `ic:"ExecuteLimitOrder,variant" json:"ExecuteLimitOrder,omitempty"`
	OneStepSwap       *OneStepSwapInfo       `ic:"OneStepSwap,variant" json:"OneStepSwap,omitempty"`
	Refund            *RefundInfo            `ic:"Refund,variant" json:"Refund,omitempty"`
	RemoveLimitOrder  *RemoveLimitOrderInfo  `ic:"RemoveLimitOrder,variant" json:"RemoveLimitOrder,omitempty"`
	Swap              *SwapInfo              `ic:"Swap,variant" json:"Swap,omitempty"`
	TransferPosition  *TransferPositionInfo  `ic:"TransferPosition,variant" json:"TransferPosition,omitempty"`
	Withdraw          *WithdrawInfo          `ic:"Withdraw,variant" json:"Withdraw,omitempty"`
}

type AccountBalance struct {
	Balance0 idl.Nat `ic:"balance0" json:"balance0"`
	Balance1 idl.Nat `ic:"balance1" json:"balance1"`
}

type Account struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *[]byte             `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type API interface {
	DepositAndSwap(arg0 DepositAndSwapArgs) (*Result, error)
	DepositFromAndSwap(arg0 DepositAndSwapArgs) (*Result, error)
}

// api is a client for the "icpswap_pair" canister.
type api struct {
	*agent.Agent
	CanisterId principal.Principal
}

// NewAPI creates a new agent for the "icrc2" canister.
func NewAPI(canisterId icp.Principal, a *icp.Agent) (*api, error) {
	return &api{
		Agent:      a.Raw(),
		CanisterId: canisterId.Raw(),
	}, nil
}

// ActiveJobs calls the "activeJobs" method on the "icpswap_pair" canister.
func (a api) ActiveJobs() error {
	if err := a.Agent.Call(
		a.CanisterId,
		"activeJobs",
		[]any{},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// AddLimitOrder calls the "addLimitOrder" method on the "icpswap_pair" canister.
func (a api) AddLimitOrder(arg0 LimitOrderArgs) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"addLimitOrder",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// AllTokenBalance calls the "allTokenBalance" method on the "icpswap_pair" canister.
func (a api) AllTokenBalance(arg0 idl.Nat, arg1 idl.Nat) (*Result32, error) {
	var r0 Result32
	if err := a.Agent.Query(
		a.CanisterId,
		"allTokenBalance",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// ApprovePosition calls the "approvePosition" method on the "icpswap_pair" canister.
func (a api) ApprovePosition(arg0 principal.Principal, arg1 idl.Nat) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"approvePosition",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// BatchRefreshIncome calls the "batchRefreshIncome" method on the "icpswap_pair" canister.
func (a api) BatchRefreshIncome(arg0 []idl.Nat) (*Result31, error) {
	var r0 Result31
	if err := a.Agent.Query(
		a.CanisterId,
		"batchRefreshIncome",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// CheckOwnerOfUserPosition calls the "checkOwnerOfUserPosition" method on the "icpswap_pair" canister.
func (a api) CheckOwnerOfUserPosition(arg0 principal.Principal, arg1 idl.Nat) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Query(
		a.CanisterId,
		"checkOwnerOfUserPosition",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Claim calls the "claim" method on the "icpswap_pair" canister.
func (a api) Claim(arg0 ClaimArgs) (*Result30, error) {
	var r0 Result30
	if err := a.Agent.Call(
		a.CanisterId,
		"claim",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DecreaseLiquidity calls the "decreaseLiquidity" method on the "icpswap_pair" canister.
func (a api) DecreaseLiquidity(arg0 DecreaseLiquidityArgs) (*Result30, error) {
	var r0 Result30
	if err := a.Agent.Call(
		a.CanisterId,
		"decreaseLiquidity",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DeleteFailedTransaction calls the "deleteFailedTransaction" method on the "icpswap_pair" canister.
func (a api) DeleteFailedTransaction(arg0 idl.Nat, arg1 bool) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"deleteFailedTransaction",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Deposit calls the "deposit" method on the "icpswap_pair" canister.
func (a api) Deposit(arg0 DepositArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"deposit",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DepositAllAndMint calls the "depositAllAndMint" method on the "icpswap_pair" canister.
func (a api) DepositAllAndMint(arg0 DepositAndMintArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"depositAllAndMint",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DepositAndSwap calls the "depositAndSwap" method on the "icpswap_pair" canister.
func (a api) DepositAndSwap(arg0 DepositAndSwapArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"depositAndSwap",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DepositFrom calls the "depositFrom" method on the "icpswap_pair" canister.
func (a api) DepositFrom(arg0 DepositArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"depositFrom",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DepositFromAndSwap calls the "depositFromAndSwap" method on the "icpswap_pair" canister.
func (a api) DepositFromAndSwap(arg0 DepositAndSwapArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"depositFromAndSwap",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetAdmins calls the "getAdmins" method on the "icpswap_pair" canister.
func (a api) GetAdmins() (*[]principal.Principal, error) {
	var r0 []principal.Principal
	if err := a.Agent.Query(
		a.CanisterId,
		"getAdmins",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetAvailabilityState calls the "getAvailabilityState" method on the "icpswap_pair" canister.
func (a api) GetAvailabilityState() (*struct {
	Available bool                  `ic:"available" json:"available"`
	WhiteList []principal.Principal `ic:"whiteList" json:"whiteList"`
}, error) {
	var r0 struct {
		Available bool                  `ic:"available" json:"available"`
		WhiteList []principal.Principal `ic:"whiteList" json:"whiteList"`
	}
	if err := a.Agent.Query(
		a.CanisterId,
		"getAvailabilityState",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetCachedTokenFee calls the "getCachedTokenFee" method on the "icpswap_pair" canister.
func (a api) GetCachedTokenFee() (*struct {
	Token0Fee idl.Nat `ic:"token0Fee" json:"token0Fee"`
	Token1Fee idl.Nat `ic:"token1Fee" json:"token1Fee"`
}, error) {
	var r0 struct {
		Token0Fee idl.Nat `ic:"token0Fee" json:"token0Fee"`
		Token1Fee idl.Nat `ic:"token1Fee" json:"token1Fee"`
	}
	if err := a.Agent.Query(
		a.CanisterId,
		"getCachedTokenFee",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetClaimLog calls the "getClaimLog" method on the "icpswap_pair" canister.
func (a api) GetClaimLog() (*[]string, error) {
	var r0 []string
	if err := a.Agent.Query(
		a.CanisterId,
		"getClaimLog",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetCycleInfo calls the "getCycleInfo" method on the "icpswap_pair" canister.
func (a api) GetCycleInfo() (*Result29, error) {
	var r0 Result29
	if err := a.Agent.Call(
		a.CanisterId,
		"getCycleInfo",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetFailedTransactions calls the "getFailedTransactions" method on the "icpswap_pair" canister.
func (a api) GetFailedTransactions() (*Result16, error) {
	var r0 Result16
	if err := a.Agent.Query(
		a.CanisterId,
		"getFailedTransactions",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetFeeGrowthGlobal calls the "getFeeGrowthGlobal" method on the "icpswap_pair" canister.
func (a api) GetFeeGrowthGlobal() (*Result28, error) {
	var r0 Result28
	if err := a.Agent.Query(
		a.CanisterId,
		"getFeeGrowthGlobal",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetInitArgs calls the "getInitArgs" method on the "icpswap_pair" canister.
func (a api) GetInitArgs() (*Result27, error) {
	var r0 Result27
	if err := a.Agent.Query(
		a.CanisterId,
		"getInitArgs",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetJobs calls the "getJobs" method on the "icpswap_pair" canister.
func (a api) GetJobs() (*struct {
	Jobs  []JobInfo `ic:"jobs" json:"jobs"`
	Level Level     `ic:"level" json:"level"`
}, error) {
	var r0 struct {
		Jobs  []JobInfo `ic:"jobs" json:"jobs"`
		Level Level     `ic:"level" json:"level"`
	}
	if err := a.Agent.Query(
		a.CanisterId,
		"getJobs",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetLimitOrderAvailabilityState calls the "getLimitOrderAvailabilityState" method on the "icpswap_pair" canister.
func (a api) GetLimitOrderAvailabilityState() (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Query(
		a.CanisterId,
		"getLimitOrderAvailabilityState",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetLimitOrderStack calls the "getLimitOrderStack" method on the "icpswap_pair" canister.
func (a api) GetLimitOrderStack() (*Result26, error) {
	var r0 Result26
	if err := a.Agent.Query(
		a.CanisterId,
		"getLimitOrderStack",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetLimitOrders calls the "getLimitOrders" method on the "icpswap_pair" canister.
func (a api) GetLimitOrders() (*Result25, error) {
	var r0 Result25
	if err := a.Agent.Query(
		a.CanisterId,
		"getLimitOrders",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetMistransferBalance calls the "getMistransferBalance" method on the "icpswap_pair" canister.
func (a api) GetMistransferBalance(arg0 Token) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"getMistransferBalance",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetPosition calls the "getPosition" method on the "icpswap_pair" canister.
func (a api) GetPosition(arg0 GetPositionArgs) (*Result24, error) {
	var r0 Result24
	if err := a.Agent.Query(
		a.CanisterId,
		"getPosition",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetPositions calls the "getPositions" method on the "icpswap_pair" canister.
func (a api) GetPositions(arg0 idl.Nat, arg1 idl.Nat) (*Result23, error) {
	var r0 Result23
	if err := a.Agent.Query(
		a.CanisterId,
		"getPositions",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetSortedUserLimitOrders calls the "getSortedUserLimitOrders" method on the "icpswap_pair" canister.
func (a api) GetSortedUserLimitOrders(arg0 principal.Principal) (*Result22, error) {
	var r0 Result22
	if err := a.Agent.Query(
		a.CanisterId,
		"getSortedUserLimitOrders",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetSwapRecordState calls the "getSwapRecordState" method on the "icpswap_pair" canister.
func (a api) GetSwapRecordState() (*Result21, error) {
	var r0 Result21
	if err := a.Agent.Query(
		a.CanisterId,
		"getSwapRecordState",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTickBitmaps calls the "getTickBitmaps" method on the "icpswap_pair" canister.
func (a api) GetTickBitmaps() (*Result20, error) {
	var r0 Result20
	if err := a.Agent.Query(
		a.CanisterId,
		"getTickBitmaps",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTickInfos calls the "getTickInfos" method on the "icpswap_pair" canister.
func (a api) GetTickInfos(arg0 idl.Nat, arg1 idl.Nat) (*Result19, error) {
	var r0 Result19
	if err := a.Agent.Query(
		a.CanisterId,
		"getTickInfos",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTicks calls the "getTicks" method on the "icpswap_pair" canister.
func (a api) GetTicks(arg0 idl.Nat, arg1 idl.Nat) (*Result18, error) {
	var r0 Result18
	if err := a.Agent.Query(
		a.CanisterId,
		"getTicks",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTokenAmountState calls the "getTokenAmountState" method on the "icpswap_pair" canister.
func (a api) GetTokenAmountState() (*Result17, error) {
	var r0 Result17
	if err := a.Agent.Query(
		a.CanisterId,
		"getTokenAmountState",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTokenBalance calls the "getTokenBalance" method on the "icpswap_pair" canister.
func (a api) GetTokenBalance() (*struct {
	Token0 idl.Nat `ic:"token0" json:"token0"`
	Token1 idl.Nat `ic:"token1" json:"token1"`
}, error) {
	var r0 struct {
		Token0 idl.Nat `ic:"token0" json:"token0"`
		Token1 idl.Nat `ic:"token1" json:"token1"`
	}
	if err := a.Agent.Call(
		a.CanisterId,
		"getTokenBalance",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTransactions calls the "getTransactions" method on the "icpswap_pair" canister.
func (a api) GetTransactions() (*Result16, error) {
	var r0 Result16
	if err := a.Agent.Query(
		a.CanisterId,
		"getTransactions",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTransactionsByOwner calls the "getTransactionsByOwner" method on the "icpswap_pair" canister.
func (a api) GetTransactionsByOwner(arg0 principal.Principal) (*Result16, error) {
	var r0 Result16
	if err := a.Agent.Query(
		a.CanisterId,
		"getTransactionsByOwner",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserByPositionId calls the "getUserByPositionId" method on the "icpswap_pair" canister.
func (a api) GetUserByPositionId(arg0 idl.Nat) (*Result1, error) {
	var r0 Result1
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserByPositionId",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserLimitOrders calls the "getUserLimitOrders" method on the "icpswap_pair" canister.
func (a api) GetUserLimitOrders(arg0 principal.Principal) (*Result15, error) {
	var r0 Result15
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserLimitOrders",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPosition calls the "getUserPosition" method on the "icpswap_pair" canister.
func (a api) GetUserPosition(arg0 idl.Nat) (*Result14, error) {
	var r0 Result14
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPosition",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPositionIds calls the "getUserPositionIds" method on the "icpswap_pair" canister.
func (a api) GetUserPositionIds() (*Result13, error) {
	var r0 Result13
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPositionIds",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPositionIdsByPrincipal calls the "getUserPositionIdsByPrincipal" method on the "icpswap_pair" canister.
func (a api) GetUserPositionIdsByPrincipal(arg0 principal.Principal) (*Result12, error) {
	var r0 Result12
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPositionIdsByPrincipal",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPositionWithTokenAmount calls the "getUserPositionWithTokenAmount" method on the "icpswap_pair" canister.
func (a api) GetUserPositionWithTokenAmount(arg0 idl.Nat, arg1 idl.Nat) (*Result11, error) {
	var r0 Result11
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPositionWithTokenAmount",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPositions calls the "getUserPositions" method on the "icpswap_pair" canister.
func (a api) GetUserPositions(arg0 idl.Nat, arg1 idl.Nat) (*Result10, error) {
	var r0 Result10
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPositions",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserPositionsByPrincipal calls the "getUserPositionsByPrincipal" method on the "icpswap_pair" canister.
func (a api) GetUserPositionsByPrincipal(arg0 principal.Principal) (*Result9, error) {
	var r0 Result9
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserPositionsByPrincipal",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetUserUnusedBalance calls the "getUserUnusedBalance" method on the "icpswap_pair" canister.
func (a api) GetUserUnusedBalance(arg0 principal.Principal) (*Result8, error) {
	var r0 Result8
	if err := a.Agent.Query(
		a.CanisterId,
		"getUserUnusedBalance",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetVersion calls the "getVersion" method on the "icpswap_pair" canister.
func (a api) GetVersion() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"getVersion",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc10SupportedStandards calls the "icrc10_supported_standards" method on the "icpswap_pair" canister.
func (a api) Icrc10SupportedStandards() (*[]struct {
	Name string `ic:"name" json:"name"`
	Url  string `ic:"url" json:"url"`
}, error) {
	var r0 []struct {
		Name string `ic:"name" json:"name"`
		Url  string `ic:"url" json:"url"`
	}
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc10_supported_standards",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc21CanisterCallConsentMessage calls the "icrc21_canister_call_consent_message" method on the "icpswap_pair" canister.
func (a api) Icrc21CanisterCallConsentMessage(arg0 Icrc21ConsentMessageRequest) (*Icrc21ConsentMessageResponse, error) {
	var r0 Icrc21ConsentMessageResponse
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc21_canister_call_consent_message",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc28TrustedOrigins calls the "icrc28_trusted_origins" method on the "icpswap_pair" canister.
func (a api) Icrc28TrustedOrigins() (*Icrc28TrustedOriginsResponse, error) {
	var r0 Icrc28TrustedOriginsResponse
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc28_trusted_origins",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// IncreaseLiquidity calls the "increaseLiquidity" method on the "icpswap_pair" canister.
func (a api) IncreaseLiquidity(arg0 IncreaseLiquidityArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"increaseLiquidity",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Init calls the "init" method on the "icpswap_pair" canister.
func (a api) Init(arg0 idl.Nat, arg1 idl.Int, arg2 idl.Nat) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"init",
		[]any{arg0, arg1, arg2},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// Metadata calls the "metadata" method on the "icpswap_pair" canister.
func (a api) Metadata() (*Result7, error) {
	var r0 Result7
	if err := a.Agent.Query(
		a.CanisterId,
		"metadata",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Mint calls the "mint" method on the "icpswap_pair" canister.
func (a api) Mint(arg0 MintArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"mint",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Quote calls the "quote" method on the "icpswap_pair" canister.
func (a api) Quote(arg0 SwapArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Query(
		a.CanisterId,
		"quote",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// QuoteForAll calls the "quoteForAll" method on the "icpswap_pair" canister.
func (a api) QuoteForAll(arg0 SwapArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Query(
		a.CanisterId,
		"quoteForAll",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RefreshIncome calls the "refreshIncome" method on the "icpswap_pair" canister.
func (a api) RefreshIncome(arg0 idl.Nat) (*Result6, error) {
	var r0 Result6
	if err := a.Agent.Query(
		a.CanisterId,
		"refreshIncome",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RemoveLimitOrder calls the "removeLimitOrder" method on the "icpswap_pair" canister.
func (a api) RemoveLimitOrder(arg0 idl.Nat) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"removeLimitOrder",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// RestartJobs calls the "restartJobs" method on the "icpswap_pair" canister.
func (a api) RestartJobs(arg0 []string) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"restartJobs",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// SetAdmins calls the "setAdmins" method on the "icpswap_pair" canister.
func (a api) SetAdmins(arg0 []principal.Principal) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"setAdmins",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// SetAvailable calls the "setAvailable" method on the "icpswap_pair" canister.
func (a api) SetAvailable(arg0 bool) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"setAvailable",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// SetIcrc28TrustedOrigins calls the "setIcrc28TrustedOrigins" method on the "icpswap_pair" canister.
func (a api) SetIcrc28TrustedOrigins(arg0 []string) (*Result5, error) {
	var r0 Result5
	if err := a.Agent.Call(
		a.CanisterId,
		"setIcrc28TrustedOrigins",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetLimitOrderAvailable calls the "setLimitOrderAvailable" method on the "icpswap_pair" canister.
func (a api) SetLimitOrderAvailable(arg0 bool) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"setLimitOrderAvailable",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// SetTokenAmountState calls the "setTokenAmountState" method on the "icpswap_pair" canister.
func (a api) SetTokenAmountState(arg0 idl.Nat, arg1 idl.Nat) (*Result4, error) {
	var r0 Result4
	if err := a.Agent.Call(
		a.CanisterId,
		"setTokenAmountState",
		[]any{arg0, arg1},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetWhiteList calls the "setWhiteList" method on the "icpswap_pair" canister.
func (a api) SetWhiteList(arg0 []principal.Principal) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"setWhiteList",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// StopJobs calls the "stopJobs" method on the "icpswap_pair" canister.
func (a api) StopJobs(arg0 []string) error {
	if err := a.Agent.Call(
		a.CanisterId,
		"stopJobs",
		[]any{arg0},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// SumTick calls the "sumTick" method on the "icpswap_pair" canister.
func (a api) SumTick() (*Result3, error) {
	var r0 Result3
	if err := a.Agent.Query(
		a.CanisterId,
		"sumTick",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Swap calls the "swap" method on the "icpswap_pair" canister.
func (a api) Swap(arg0 SwapArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"swap",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// TransferPosition calls the "transferPosition" method on the "icpswap_pair" canister.
func (a api) TransferPosition(arg0 principal.Principal, arg1 principal.Principal, arg2 idl.Nat) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"transferPosition",
		[]any{arg0, arg1, arg2},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// UpdateTokenFee calls the "updateTokenFee" method on the "icpswap_pair" canister.
func (a api) UpdateTokenFee() error {
	if err := a.Agent.Call(
		a.CanisterId,
		"updateTokenFee",
		[]any{},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// UpgradeTokenStandard calls the "upgradeTokenStandard" method on the "icpswap_pair" canister.
func (a api) UpgradeTokenStandard(arg0 principal.Principal) (*Result1, error) {
	var r0 Result1
	if err := a.Agent.Call(
		a.CanisterId,
		"upgradeTokenStandard",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Withdraw calls the "withdraw" method on the "icpswap_pair" canister.
func (a api) Withdraw(arg0 WithdrawArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"withdraw",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// WithdrawMistransferBalance calls the "withdrawMistransferBalance" method on the "icpswap_pair" canister.
func (a api) WithdrawMistransferBalance(arg0 Token) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"withdrawMistransferBalance",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// WithdrawToSubaccount calls the "withdrawToSubaccount" method on the "icpswap_pair" canister.
func (a api) WithdrawToSubaccount(arg0 WithdrawToSubaccountArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"withdrawToSubaccount",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}
