// Package icrc1 provides a client for the "icrc1" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package icrc1

import (
	"fmt"

	"github.com/aviate-labs/agent-go"
	"github.com/aviate-labs/agent-go/candid/idl"
	"github.com/aviate-labs/agent-go/principal"
	"github.com/niccolofant/ic-arb/core/icp"
)

type Value struct {
	Blob *[]byte  `ic:"Blob,variant" json:"Blob,omitempty"`
	Int  *idl.Int `ic:"Int,variant" json:"Int,omitempty"`
	Nat  *idl.Nat `ic:"Nat,variant" json:"Nat,omitempty"`
	Text *string  `ic:"Text,variant" json:"Text,omitempty"`
}

type TxIndex = idl.Nat

type TransferResult struct {
	Err *TransferError `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *TxIndex       `ic:"Ok,variant" json:"Ok,omitempty"`
}

type TransferError struct {
	BadBurn *struct {
		MinBurnAmount Balance `ic:"min_burn_amount" json:"min_burn_amount"`
	} `ic:"BadBurn,variant" json:"BadBurn,omitempty"`
	BadFee *struct {
		ExpectedFee Balance `ic:"expected_fee" json:"expected_fee"`
	} `ic:"BadFee,variant" json:"BadFee,omitempty"`
	CreatedInFuture *struct {
		LedgerTime Timestamp `ic:"ledger_time" json:"ledger_time"`
	} `ic:"CreatedInFuture,variant" json:"CreatedInFuture,omitempty"`
	Duplicate *struct {
		DuplicateOf TxIndex `ic:"duplicate_of" json:"duplicate_of"`
	} `ic:"Duplicate,variant" json:"Duplicate,omitempty"`
	GenericError *struct {
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
		Message   string  `ic:"message" json:"message"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	InsufficientFunds *struct {
		Balance Balance `ic:"balance" json:"balance"`
	} `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
	TemporarilyUnavailable *idl.Null `ic:"TemporarilyUnavailable,variant" json:"TemporarilyUnavailable,omitempty"`
	TooOld                 *idl.Null `ic:"TooOld,variant" json:"TooOld,omitempty"`
}

func (e TransferError) Decode() error {
	switch {
	case e.BadBurn != nil:
		return fmt.Errorf("bad burn: minimum burn amount required is %v", e.BadBurn.MinBurnAmount)
	case e.BadFee != nil:
		return fmt.Errorf("bad fee: expected fee is %v", e.BadFee.ExpectedFee)
	case e.CreatedInFuture != nil:
		return fmt.Errorf("transaction created in the future (ledger time: %d)", e.CreatedInFuture.LedgerTime)
	case e.Duplicate != nil:
		return fmt.Errorf("duplicate transaction (duplicate of tx index: %v)", e.Duplicate.DuplicateOf)
	case e.GenericError != nil:
		return fmt.Errorf("generic error (code %v): %s", e.GenericError.ErrorCode, e.GenericError.Message)
	case e.InsufficientFunds != nil:
		return fmt.Errorf("insufficient funds: balance is %v", e.InsufficientFunds.Balance)
	case e.TemporarilyUnavailable != nil:
		return fmt.Errorf("temporarily unavailable")
	case e.TooOld != nil:
		return fmt.Errorf("transaction too old")
	default:
		return fmt.Errorf("unknown transfer error")
	}
}

type TransferArgs struct {
	Amount         Balance     `ic:"amount" json:"amount"`
	CreatedAtTime  *uint64     `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Fee            *Balance    `ic:"fee,omitempty" json:"fee,omitempty"`
	FromSubaccount *Subaccount `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	Memo           *[]byte     `ic:"memo,omitempty" json:"memo,omitempty"`
	To             Account     `ic:"to" json:"to"`
}

type Transfer struct {
	Amount        Balance  `ic:"amount" json:"amount"`
	CreatedAtTime *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Fee           *Balance `ic:"fee,omitempty" json:"fee,omitempty"`
	From          Account  `ic:"from" json:"from"`
	Memo          *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	To            Account  `ic:"to" json:"to"`
}

type TransactionRange struct {
	Transactions []Transaction `ic:"transactions" json:"transactions"`
}

type Transaction struct {
	Burn      *Burn     `ic:"burn,omitempty" json:"burn,omitempty"`
	Index     TxIndex   `ic:"index" json:"index"`
	Kind      string    `ic:"kind" json:"kind"`
	Mint      *Mint     `ic:"mint,omitempty" json:"mint,omitempty"`
	Timestamp Timestamp `ic:"timestamp" json:"timestamp"`
	Transfer  *Transfer `ic:"transfer,omitempty" json:"transfer,omitempty"`
}

type TokenInitArgs struct {
	AdvancedSettings *AdvancedSettings `ic:"advanced_settings,omitempty" json:"advanced_settings,omitempty"`
	Decimals         uint8             `ic:"decimals" json:"decimals"`
	Fee              Balance           `ic:"fee" json:"fee"`
	InitialBalances  []struct {
		Field0 Account `ic:"0,tuple" json:"0,tuple"`
		Field1 Balance `ic:"1,tuple" json:"1,tuple"`
	} `ic:"initial_balances" json:"initial_balances"`
	Logo           string   `ic:"logo" json:"logo"`
	MaxSupply      Balance  `ic:"max_supply" json:"max_supply"`
	MinBurnAmount  Balance  `ic:"min_burn_amount" json:"min_burn_amount"`
	MintingAccount *Account `ic:"minting_account,omitempty" json:"minting_account,omitempty"`
	Name           string   `ic:"name" json:"name"`
	Symbol         string   `ic:"symbol" json:"symbol"`
}

type Timestamp = uint64

type SupportedStandard struct {
	Name string `ic:"name" json:"name"`
	Url  string `ic:"url" json:"url"`
}

type Subaccount = []byte

type SetTextParameterResult struct {
	Err *SetParameterError `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *string            `ic:"Ok,variant" json:"Ok,omitempty"`
}

type SetParameterError struct {
	GenericError *struct {
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
		Message   string  `ic:"message" json:"message"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
}

type SetNat8ParameterResult struct {
	Err *SetParameterError `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *uint8             `ic:"Ok,variant" json:"Ok,omitempty"`
}

type SetBalanceParameterResult struct {
	Err *SetParameterError `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *Balance           `ic:"Ok,variant" json:"Ok,omitempty"`
}

type SetAccountParameterResult struct {
	Err *SetParameterError `ic:"Err,variant" json:"Err,omitempty"`
	Ok  *Account           `ic:"Ok,variant" json:"Ok,omitempty"`
}

type Result1 struct {
	Err *string   `ic:"err,variant" json:"err,omitempty"`
	Ok  *idl.Null `ic:"ok,variant" json:"ok,omitempty"`
}

type Result struct {
	Err *string         `ic:"err,variant" json:"err,omitempty"`
	Ok  *[]BalanceEntry `ic:"ok,variant" json:"ok,omitempty"`
}

type QueryArchiveFn = idl.Function

type Mint struct {
	Amount        Balance `ic:"amount" json:"amount"`
	CreatedAtTime *uint64 `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Memo          *[]byte `ic:"memo,omitempty" json:"memo,omitempty"`
	To            Account `ic:"to" json:"to"`
}

type MetaDatum struct {
	Field0 string `ic:"0,tuple" json:"0,tuple"`
	Field1 Value  `ic:"1,tuple" json:"1,tuple"`
}

type GetTransactionsResponse struct {
	ArchivedTransactions []ArchivedTransaction `ic:"archived_transactions" json:"archived_transactions"`
	FirstIndex           TxIndex               `ic:"first_index" json:"first_index"`
	LogLength            idl.Nat               `ic:"log_length" json:"log_length"`
	Transactions         []Transaction         `ic:"transactions" json:"transactions"`
}

type GetTransactionsRequest struct {
	Length idl.Nat `ic:"length" json:"length"`
	Start  TxIndex `ic:"start" json:"start"`
}

type BurnArgs struct {
	Amount         Balance     `ic:"amount" json:"amount"`
	CreatedAtTime  *uint64     `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	FromSubaccount *Subaccount `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	Memo           *[]byte     `ic:"memo,omitempty" json:"memo,omitempty"`
}

type Burn struct {
	Amount        Balance `ic:"amount" json:"amount"`
	CreatedAtTime *uint64 `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	From          Account `ic:"from" json:"from"`
	Memo          *[]byte `ic:"memo,omitempty" json:"memo,omitempty"`
}

type BalanceEntry struct {
	Account Account `ic:"account" json:"account"`
	Balance Balance `ic:"balance" json:"balance"`
}

type Balance = idl.Nat

type ArchivedTransaction struct {
	Callback QueryArchiveFn `ic:"callback" json:"callback"`
	Length   idl.Nat        `ic:"length" json:"length"`
	Start    TxIndex        `ic:"start" json:"start"`
}

type AdvancedSettings struct {
	BurnedTokens      Balance   `ic:"burned_tokens" json:"burned_tokens"`
	PermittedDrift    Timestamp `ic:"permitted_drift" json:"permitted_drift"`
	TransactionWindow Timestamp `ic:"transaction_window" json:"transaction_window"`
}

type Account struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *Subaccount         `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type API interface {
	Icrc1Transfer(args TransferArgs) (*TransferResult, error)
	Icrc1BalanceOf(args Account) (*Balance, error)
	Icrc1Metadata() (*[]MetaDatum, error)
}

// api is a client for the "icrc1" canister.
type api struct {
	*agent.Agent
	CanisterId principal.Principal
}

// NewAPI creates a new agent for the "icrc1" canister.
func NewAPI(canisterId icp.Principal, a *icp.Agent) (*api, error) {
	return &api{
		Agent:      a.Raw(),
		CanisterId: canisterId.Raw(),
	}, nil
}

// Burn calls the "burn" method on the "icrc1" canister.
func (a api) Burn(args BurnArgs) (*TransferResult, error) {
	var r0 TransferResult
	if err := a.Agent.Call(
		a.CanisterId,
		"burn",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// DepositCycles calls the "deposit_cycles" method on the "icrc1" canister.
func (a api) DepositCycles() error {
	if err := a.Agent.Call(
		a.CanisterId,
		"deposit_cycles",
		[]any{},
		[]any{},
	); err != nil {
		return err
	}
	return nil
}

// GetArchiveStoredTxs calls the "get_archive_stored_txs" method on the "icrc1" canister.
func (a api) GetArchiveStoredTxs() (*idl.Nat, error) {
	var r0 idl.Nat
	if err := a.Agent.Query(
		a.CanisterId,
		"get_archive_stored_txs",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetBalances calls the "get_balances" method on the "icrc1" canister.
func (a api) GetBalances(start idl.Nat, length idl.Nat) (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"get_balances",
		[]any{start, length},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetBalancesSimple calls the "get_balances_simple" method on the "icrc1" canister.
func (a api) GetBalancesSimple() (*Result, error) {
	var r0 Result
	if err := a.Agent.Call(
		a.CanisterId,
		"get_balances_simple",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTotalTx calls the "get_total_tx" method on the "icrc1" canister.
func (a api) GetTotalTx() (*idl.Nat, error) {
	var r0 idl.Nat
	if err := a.Agent.Query(
		a.CanisterId,
		"get_total_tx",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTransaction calls the "get_transaction" method on the "icrc1" canister.
func (a api) GetTransaction(i TxIndex) (**Transaction, error) {
	var r0 *Transaction
	if err := a.Agent.Call(
		a.CanisterId,
		"get_transaction",
		[]any{i},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTransactions calls the "get_transactions" method on the "icrc1" canister.
func (a api) GetTransactions(req GetTransactionsRequest) (*GetTransactionsResponse, error) {
	var r0 GetTransactionsResponse
	if err := a.Agent.Query(
		a.CanisterId,
		"get_transactions",
		[]any{req},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1BalanceOf calls the "icrc1_balance_of" method on the "icrc1" canister.
func (a api) Icrc1BalanceOf(args Account) (*Balance, error) {
	var r0 Balance
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_balance_of",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Decimals calls the "icrc1_decimals" method on the "icrc1" canister.
func (a api) Icrc1Decimals() (*uint8, error) {
	var r0 uint8
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_decimals",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Fee calls the "icrc1_fee" method on the "icrc1" canister.
func (a api) Icrc1Fee() (*Balance, error) {
	var r0 Balance
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_fee",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Metadata calls the "icrc1_metadata" method on the "icrc1" canister.
func (a api) Icrc1Metadata() (*[]MetaDatum, error) {
	var r0 []MetaDatum
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_metadata",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1MintingAccount calls the "icrc1_minting_account" method on the "icrc1" canister.
func (a api) Icrc1MintingAccount() (**Account, error) {
	var r0 *Account
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_minting_account",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Name calls the "icrc1_name" method on the "icrc1" canister.
func (a api) Icrc1Name() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_name",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1SupportedStandards calls the "icrc1_supported_standards" method on the "icrc1" canister.
func (a api) Icrc1SupportedStandards() (*[]SupportedStandard, error) {
	var r0 []SupportedStandard
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_supported_standards",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Symbol calls the "icrc1_symbol" method on the "icrc1" canister.
func (a api) Icrc1Symbol() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_symbol",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1TotalSupply calls the "icrc1_total_supply" method on the "icrc1" canister.
func (a api) Icrc1TotalSupply() (*Balance, error) {
	var r0 Balance
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_total_supply",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Transfer calls the "icrc1_transfer" method on the "icrc1" canister.
func (a api) Icrc1Transfer(args TransferArgs) (*TransferResult, error) {
	var r0 TransferResult
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc1_transfer",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// MinBurnAmount calls the "min_burn_amount" method on the "icrc1" canister.
func (a api) MinBurnAmount() (*Balance, error) {
	var r0 Balance
	if err := a.Agent.Query(
		a.CanisterId,
		"min_burn_amount",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Mint calls the "mint" method on the "icrc1" canister.
func (a api) Mint(args Mint) (*TransferResult, error) {
	var r0 TransferResult
	if err := a.Agent.Call(
		a.CanisterId,
		"mint",
		[]any{args},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetDecimals calls the "set_decimals" method on the "icrc1" canister.
func (a api) SetDecimals(decimals uint8) (*SetNat8ParameterResult, error) {
	var r0 SetNat8ParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_decimals",
		[]any{decimals},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetFee calls the "set_fee" method on the "icrc1" canister.
func (a api) SetFee(fee Balance) (*SetBalanceParameterResult, error) {
	var r0 SetBalanceParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_fee",
		[]any{fee},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetLogo calls the "set_logo" method on the "icrc1" canister.
func (a api) SetLogo(logo string) (*SetTextParameterResult, error) {
	var r0 SetTextParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_logo",
		[]any{logo},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetMinBurnAmount calls the "set_min_burn_amount" method on the "icrc1" canister.
func (a api) SetMinBurnAmount(min_burn_amount Balance) (*SetBalanceParameterResult, error) {
	var r0 SetBalanceParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_min_burn_amount",
		[]any{min_burn_amount},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetMintingAccount calls the "set_minting_account" method on the "icrc1" canister.
func (a api) SetMintingAccount(minting_account string) (*SetAccountParameterResult, error) {
	var r0 SetAccountParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_minting_account",
		[]any{minting_account},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetName calls the "set_name" method on the "icrc1" canister.
func (a api) SetName(name string) (*SetTextParameterResult, error) {
	var r0 SetTextParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_name",
		[]any{name},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// SetSymbol calls the "set_symbol" method on the "icrc1" canister.
func (a api) SetSymbol(symbol string) (*SetTextParameterResult, error) {
	var r0 SetTextParameterResult
	if err := a.Agent.Call(
		a.CanisterId,
		"set_symbol",
		[]any{symbol},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}
