// Package icrc2 provides a client for the "icrc2" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package icrc2

import (
	"fmt"

	"github.com/aviate-labs/agent-go"
	"github.com/aviate-labs/agent-go/candid/idl"
	"github.com/aviate-labs/agent-go/principal"
	"github.com/niccolofant/ic-arb/icp"
)

type Account struct {
	Owner      principal.Principal `ic:"owner" json:"owner"`
	Subaccount *[]byte             `ic:"subaccount,omitempty" json:"subaccount,omitempty"`
}

type Allowance struct {
	FromAccount Account `ic:"from_account" json:"from_account"`
	ToSpender   Account `ic:"to_spender" json:"to_spender"`
	Allowance   idl.Nat `ic:"allowance" json:"allowance"`
	ExpiresAt   *uint64 `ic:"expires_at,omitempty" json:"expires_at,omitempty"`
}

type AllowanceArgs struct {
	Account Account `ic:"account" json:"account"`
	Spender Account `ic:"spender" json:"spender"`
}

type Allowance1 struct {
	Allowance idl.Nat `ic:"allowance" json:"allowance"`
	ExpiresAt *uint64 `ic:"expires_at,omitempty" json:"expires_at,omitempty"`
}

type Approve struct {
	Fee               *idl.Nat `ic:"fee,omitempty" json:"fee,omitempty"`
	From              Account  `ic:"from" json:"from"`
	Memo              *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	CreatedAtTime     *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount            idl.Nat  `ic:"amount" json:"amount"`
	ExpectedAllowance *idl.Nat `ic:"expected_allowance,omitempty" json:"expected_allowance,omitempty"`
	ExpiresAt         *uint64  `ic:"expires_at,omitempty" json:"expires_at,omitempty"`
	Spender           Account  `ic:"spender" json:"spender"`
}

type ApproveArgs struct {
	Fee               *idl.Nat `ic:"fee,omitempty" json:"fee,omitempty"`
	Memo              *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	FromSubaccount    *[]byte  `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	CreatedAtTime     *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount            idl.Nat  `ic:"amount" json:"amount"`
	ExpectedAllowance *idl.Nat `ic:"expected_allowance,omitempty" json:"expected_allowance,omitempty"`
	ExpiresAt         *uint64  `ic:"expires_at,omitempty" json:"expires_at,omitempty"`
	Spender           Account  `ic:"spender" json:"spender"`
}

type ApproveError struct {
	GenericError *struct {
		Message   string  `ic:"message" json:"message"`
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	TemporarilyUnavailable *idl.Null `ic:"TemporarilyUnavailable,variant" json:"TemporarilyUnavailable,omitempty"`
	Duplicate              *struct {
		DuplicateOf idl.Nat `ic:"duplicate_of" json:"duplicate_of"`
	} `ic:"Duplicate,variant" json:"Duplicate,omitempty"`
	BadFee *struct {
		ExpectedFee idl.Nat `ic:"expected_fee" json:"expected_fee"`
	} `ic:"BadFee,variant" json:"BadFee,omitempty"`
	AllowanceChanged *struct {
		CurrentAllowance idl.Nat `ic:"current_allowance" json:"current_allowance"`
	} `ic:"AllowanceChanged,variant" json:"AllowanceChanged,omitempty"`
	CreatedInFuture *struct {
		LedgerTime uint64 `ic:"ledger_time" json:"ledger_time"`
	} `ic:"CreatedInFuture,variant" json:"CreatedInFuture,omitempty"`
	TooOld  *idl.Null `ic:"TooOld,variant" json:"TooOld,omitempty"`
	Expired *struct {
		LedgerTime uint64 `ic:"ledger_time" json:"ledger_time"`
	} `ic:"Expired,variant" json:"Expired,omitempty"`
	InsufficientFunds *struct {
		Balance idl.Nat `ic:"balance" json:"balance"`
	} `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
}

func (e ApproveError) Decode() error {
	switch {
	case e.GenericError != nil:
		return fmt.Errorf("generic error: %s (code: %v)", e.GenericError.Message, e.GenericError.ErrorCode)

	case e.TemporarilyUnavailable != nil:
		return fmt.Errorf("temporarily unavailable")

	case e.Duplicate != nil:
		return fmt.Errorf("duplicate request (duplicate of: %v)", e.Duplicate.DuplicateOf)

	case e.BadFee != nil:
		return fmt.Errorf("bad fee: expected fee %v", e.BadFee.ExpectedFee)

	case e.AllowanceChanged != nil:
		return fmt.Errorf("allowance changed: current allowance %v", e.AllowanceChanged.CurrentAllowance)

	case e.CreatedInFuture != nil:
		return fmt.Errorf("created in future: ledger time %d", e.CreatedInFuture.LedgerTime)

	case e.TooOld != nil:
		return fmt.Errorf("transaction too old")

	case e.Expired != nil:
		return fmt.Errorf("transaction expired: ledger time %d", e.Expired.LedgerTime)

	case e.InsufficientFunds != nil:
		return fmt.Errorf("insufficient funds: balance %v", e.InsufficientFunds.Balance)

	default:
		return fmt.Errorf("unknown approve error")
	}
}

type ArchiveInfo struct {
	BlockRangeEnd   idl.Nat             `ic:"block_range_end" json:"block_range_end"`
	CanisterId      principal.Principal `ic:"canister_id" json:"canister_id"`
	BlockRangeStart idl.Nat             `ic:"block_range_start" json:"block_range_start"`
}

type ArchiveOptions struct {
	NumBlocksToArchive         uint64                 `ic:"num_blocks_to_archive" json:"num_blocks_to_archive"`
	MaxTransactionsPerResponse *uint64                `ic:"max_transactions_per_response,omitempty" json:"max_transactions_per_response,omitempty"`
	TriggerThreshold           uint64                 `ic:"trigger_threshold" json:"trigger_threshold"`
	MoreControllerIds          *[]principal.Principal `ic:"more_controller_ids,omitempty" json:"more_controller_ids,omitempty"`
	MaxMessageSizeBytes        *uint64                `ic:"max_message_size_bytes,omitempty" json:"max_message_size_bytes,omitempty"`
	CyclesForArchiveCreation   *uint64                `ic:"cycles_for_archive_creation,omitempty" json:"cycles_for_archive_creation,omitempty"`
	NodeMaxMemorySizeBytes     *uint64                `ic:"node_max_memory_size_bytes,omitempty" json:"node_max_memory_size_bytes,omitempty"`
	ControllerId               principal.Principal    `ic:"controller_id" json:"controller_id"`
}

type ArchivedBlocks struct {
	Args     []GetBlocksRequest `ic:"args" json:"args"`
	Callback idl.Function       `ic:"callback" json:"callback"`
}

type ArchivedRange struct {
	Callback idl.Function `ic:"callback" json:"callback"`
	Start    idl.Nat      `ic:"start" json:"start"`
	Length   idl.Nat      `ic:"length" json:"length"`
}

type ArchivedRange1 struct {
	Callback idl.Function `ic:"callback" json:"callback"`
	Start    idl.Nat      `ic:"start" json:"start"`
	Length   idl.Nat      `ic:"length" json:"length"`
}

type BlockRange struct {
	Blocks []Value `ic:"blocks" json:"blocks"`
}

type BlockWithId struct {
	Id    idl.Nat    `ic:"id" json:"id"`
	Block ICRC3Value `ic:"block" json:"block"`
}

type Burn struct {
	From          Account  `ic:"from" json:"from"`
	Memo          *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	CreatedAtTime *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount        idl.Nat  `ic:"amount" json:"amount"`
	Spender       *Account `ic:"spender,omitempty" json:"spender,omitempty"`
}

type ChangeArchiveOptions struct {
	NumBlocksToArchive         *uint64                `ic:"num_blocks_to_archive,omitempty" json:"num_blocks_to_archive,omitempty"`
	MaxTransactionsPerResponse *uint64                `ic:"max_transactions_per_response,omitempty" json:"max_transactions_per_response,omitempty"`
	TriggerThreshold           *uint64                `ic:"trigger_threshold,omitempty" json:"trigger_threshold,omitempty"`
	MoreControllerIds          *[]principal.Principal `ic:"more_controller_ids,omitempty" json:"more_controller_ids,omitempty"`
	MaxMessageSizeBytes        *uint64                `ic:"max_message_size_bytes,omitempty" json:"max_message_size_bytes,omitempty"`
	CyclesForArchiveCreation   *uint64                `ic:"cycles_for_archive_creation,omitempty" json:"cycles_for_archive_creation,omitempty"`
	NodeMaxMemorySizeBytes     *uint64                `ic:"node_max_memory_size_bytes,omitempty" json:"node_max_memory_size_bytes,omitempty"`
	ControllerId               *principal.Principal   `ic:"controller_id,omitempty" json:"controller_id,omitempty"`
}

type ChangeFeeCollector struct {
	SetTo *Account  `ic:"SetTo,variant" json:"SetTo,omitempty"`
	Unset *idl.Null `ic:"Unset,variant" json:"Unset,omitempty"`
}

type ConsentInfo struct {
	Metadata       ConsentMessageMetadata `ic:"metadata" json:"metadata"`
	ConsentMessage ConsentMessage         `ic:"consent_message" json:"consent_message"`
}

type ConsentMessage struct {
	FieldsDisplayMessage  *FieldsDisplay `ic:"FieldsDisplayMessage,variant" json:"FieldsDisplayMessage,omitempty"`
	GenericDisplayMessage *string        `ic:"GenericDisplayMessage,variant" json:"GenericDisplayMessage,omitempty"`
}

type ConsentMessageMetadata struct {
	UtcOffsetMinutes *int16 `ic:"utc_offset_minutes,omitempty" json:"utc_offset_minutes,omitempty"`
	Language         string `ic:"language" json:"language"`
}

type ConsentMessageRequest struct {
	Arg             []byte             `ic:"arg" json:"arg"`
	Method          string             `ic:"method" json:"method"`
	UserPreferences ConsentMessageSpec `ic:"user_preferences" json:"user_preferences"`
}

type ConsentMessageSpec struct {
	Metadata   ConsentMessageMetadata `ic:"metadata" json:"metadata"`
	DeviceSpec *DisplayMessageType    `ic:"device_spec,omitempty" json:"device_spec,omitempty"`
}

type DataCertificate struct {
	Certificate *[]byte `ic:"certificate,omitempty" json:"certificate,omitempty"`
	HashTree    []byte  `ic:"hash_tree" json:"hash_tree"`
}

type DisplayMessageType struct {
	GenericDisplay *idl.Null `ic:"GenericDisplay,variant" json:"GenericDisplay,omitempty"`
	FieldsDisplay  *idl.Null `ic:"FieldsDisplay,variant" json:"FieldsDisplay,omitempty"`
}

type ErrorInfo struct {
	Description string `ic:"description" json:"description"`
}

type FeatureFlags struct {
	Icrc2 bool `ic:"icrc2" json:"icrc2"`
}

type FieldsDisplay struct {
	Fields []struct {
		Field0 string `ic:"0,tuple" json:"0,tuple"`
		Field1 Value1 `ic:"1,tuple" json:"1,tuple"`
	} `ic:"fields" json:"fields"`
	Intent string `ic:"intent" json:"intent"`
}

type GetAllowancesArgs struct {
	Take        *idl.Nat `ic:"take,omitempty" json:"take,omitempty"`
	PrevSpender *Account `ic:"prev_spender,omitempty" json:"prev_spender,omitempty"`
	FromAccount *Account `ic:"from_account,omitempty" json:"from_account,omitempty"`
}

type GetAllowancesError struct {
	GenericError *struct {
		Message   string  `ic:"message" json:"message"`
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	AccessDenied *struct {
		Reason string `ic:"reason" json:"reason"`
	} `ic:"AccessDenied,variant" json:"AccessDenied,omitempty"`
}

type GetArchivesArgs struct {
	From *principal.Principal `ic:"from,omitempty" json:"from,omitempty"`
}

type GetBlocksRequest struct {
	Start  idl.Nat `ic:"start" json:"start"`
	Length idl.Nat `ic:"length" json:"length"`
}

type GetBlocksResponse struct {
	Certificate    *[]byte         `ic:"certificate,omitempty" json:"certificate,omitempty"`
	FirstIndex     idl.Nat         `ic:"first_index" json:"first_index"`
	Blocks         []Value         `ic:"blocks" json:"blocks"`
	ChainLength    uint64          `ic:"chain_length" json:"chain_length"`
	ArchivedBlocks []ArchivedRange `ic:"archived_blocks" json:"archived_blocks"`
}

type GetBlocksResult struct {
	LogLength      idl.Nat          `ic:"log_length" json:"log_length"`
	Blocks         []BlockWithId    `ic:"blocks" json:"blocks"`
	ArchivedBlocks []ArchivedBlocks `ic:"archived_blocks" json:"archived_blocks"`
}

type GetTransactionsResponse struct {
	FirstIndex           idl.Nat          `ic:"first_index" json:"first_index"`
	LogLength            idl.Nat          `ic:"log_length" json:"log_length"`
	Transactions         []Transaction    `ic:"transactions" json:"transactions"`
	ArchivedTransactions []ArchivedRange1 `ic:"archived_transactions" json:"archived_transactions"`
}

type ICRC3ArchiveInfo struct {
	End        idl.Nat             `ic:"end" json:"end"`
	CanisterId principal.Principal `ic:"canister_id" json:"canister_id"`
	Start      idl.Nat             `ic:"start" json:"start"`
}

type ICRC3DataCertificate struct {
	Certificate []byte `ic:"certificate" json:"certificate"`
	HashTree    []byte `ic:"hash_tree" json:"hash_tree"`
}

type ICRC3Value struct {
	Int *idl.Int `ic:"Int,variant" json:"Int,omitempty"`
	Map *[]struct {
		Field0 string     `ic:"0,tuple" json:"0,tuple"`
		Field1 ICRC3Value `ic:"1,tuple" json:"1,tuple"`
	} `ic:"Map,variant" json:"Map,omitempty"`
	Nat   *idl.Nat      `ic:"Nat,variant" json:"Nat,omitempty"`
	Blob  *[]byte       `ic:"Blob,variant" json:"Blob,omitempty"`
	Text  *string       `ic:"Text,variant" json:"Text,omitempty"`
	Array *[]ICRC3Value `ic:"Array,variant" json:"Array,omitempty"`
}

type Icrc106Error struct {
	GenericError *struct {
		Description string  `ic:"description" json:"description"`
		ErrorCode   idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	IndexPrincipalNotSet *idl.Null `ic:"IndexPrincipalNotSet,variant" json:"IndexPrincipalNotSet,omitempty"`
}

type Icrc21Error struct {
	GenericError *struct {
		Description string  `ic:"description" json:"description"`
		ErrorCode   idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	InsufficientPayment       *ErrorInfo `ic:"InsufficientPayment,variant" json:"InsufficientPayment,omitempty"`
	UnsupportedCanisterCall   *ErrorInfo `ic:"UnsupportedCanisterCall,variant" json:"UnsupportedCanisterCall,omitempty"`
	ConsentMessageUnavailable *ErrorInfo `ic:"ConsentMessageUnavailable,variant" json:"ConsentMessageUnavailable,omitempty"`
}

type InitArgs struct {
	Decimals    *uint8  `ic:"decimals,omitempty" json:"decimals,omitempty"`
	TokenSymbol string  `ic:"token_symbol" json:"token_symbol"`
	TransferFee idl.Nat `ic:"transfer_fee" json:"transfer_fee"`
	Metadata    []struct {
		Field0 string        `ic:"0,tuple" json:"0,tuple"`
		Field1 MetadataValue `ic:"1,tuple" json:"1,tuple"`
	} `ic:"metadata" json:"metadata"`
	MintingAccount  Account `ic:"minting_account" json:"minting_account"`
	InitialBalances []struct {
		Field0 Account `ic:"0,tuple" json:"0,tuple"`
		Field1 idl.Nat `ic:"1,tuple" json:"1,tuple"`
	} `ic:"initial_balances" json:"initial_balances"`
	FeeCollectorAccount *Account             `ic:"fee_collector_account,omitempty" json:"fee_collector_account,omitempty"`
	ArchiveOptions      ArchiveOptions       `ic:"archive_options" json:"archive_options"`
	MaxMemoLength       *uint16              `ic:"max_memo_length,omitempty" json:"max_memo_length,omitempty"`
	IndexPrincipal      *principal.Principal `ic:"index_principal,omitempty" json:"index_principal,omitempty"`
	TokenName           string               `ic:"token_name" json:"token_name"`
	FeatureFlags        *FeatureFlags        `ic:"feature_flags,omitempty" json:"feature_flags,omitempty"`
}

type LedgerArgument struct {
	Upgrade **UpgradeArgs `ic:"Upgrade,variant" json:"Upgrade,omitempty"`
	Init    *InitArgs     `ic:"Init,variant" json:"Init,omitempty"`
}

type MetadataValue struct {
	Int  *idl.Int `ic:"Int,variant" json:"Int,omitempty"`
	Nat  *idl.Nat `ic:"Nat,variant" json:"Nat,omitempty"`
	Blob *[]byte  `ic:"Blob,variant" json:"Blob,omitempty"`
	Text *string  `ic:"Text,variant" json:"Text,omitempty"`
}

type Mint struct {
	To            Account `ic:"to" json:"to"`
	Memo          *[]byte `ic:"memo,omitempty" json:"memo,omitempty"`
	CreatedAtTime *uint64 `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount        idl.Nat `ic:"amount" json:"amount"`
}

type Result struct {
	Ok  *[]Allowance        `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *GetAllowancesError `ic:"Err,variant" json:"Err,omitempty"`
}

type Result1 struct {
	Ok  *principal.Principal `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *Icrc106Error        `ic:"Err,variant" json:"Err,omitempty"`
}

type Result2 struct {
	Ok  *idl.Nat       `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *TransferError `ic:"Err,variant" json:"Err,omitempty"`
}

type Result3 struct {
	Ok  *ConsentInfo `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *Icrc21Error `ic:"Err,variant" json:"Err,omitempty"`
}

type Result4 struct {
	Ok  *idl.Nat      `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApproveError `ic:"Err,variant" json:"Err,omitempty"`
}

type Result5 struct {
	Ok  *idl.Nat           `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *TransferFromError `ic:"Err,variant" json:"Err,omitempty"`
}

type StandardRecord struct {
	Url  string `ic:"url" json:"url"`
	Name string `ic:"name" json:"name"`
}

type SupportedBlockType struct {
	Url       string `ic:"url" json:"url"`
	BlockType string `ic:"block_type" json:"block_type"`
}

type Transaction struct {
	Burn      *Burn     `ic:"burn,omitempty" json:"burn,omitempty"`
	Kind      string    `ic:"kind" json:"kind"`
	Mint      *Mint     `ic:"mint,omitempty" json:"mint,omitempty"`
	Approve   *Approve  `ic:"approve,omitempty" json:"approve,omitempty"`
	Timestamp uint64    `ic:"timestamp" json:"timestamp"`
	Transfer  *Transfer `ic:"transfer,omitempty" json:"transfer,omitempty"`
}

type TransactionRange struct {
	Transactions []Transaction `ic:"transactions" json:"transactions"`
}

type Transfer struct {
	To            Account  `ic:"to" json:"to"`
	Fee           *idl.Nat `ic:"fee,omitempty" json:"fee,omitempty"`
	From          Account  `ic:"from" json:"from"`
	Memo          *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	CreatedAtTime *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount        idl.Nat  `ic:"amount" json:"amount"`
	Spender       *Account `ic:"spender,omitempty" json:"spender,omitempty"`
}

type TransferArg struct {
	To             Account  `ic:"to" json:"to"`
	Fee            *idl.Nat `ic:"fee,omitempty" json:"fee,omitempty"`
	Memo           *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	FromSubaccount *[]byte  `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	CreatedAtTime  *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount         idl.Nat  `ic:"amount" json:"amount"`
}

type TransferError struct {
	GenericError *struct {
		Message   string  `ic:"message" json:"message"`
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	TemporarilyUnavailable *idl.Null `ic:"TemporarilyUnavailable,variant" json:"TemporarilyUnavailable,omitempty"`
	BadBurn                *struct {
		MinBurnAmount idl.Nat `ic:"min_burn_amount" json:"min_burn_amount"`
	} `ic:"BadBurn,variant" json:"BadBurn,omitempty"`
	Duplicate *struct {
		DuplicateOf idl.Nat `ic:"duplicate_of" json:"duplicate_of"`
	} `ic:"Duplicate,variant" json:"Duplicate,omitempty"`
	BadFee *struct {
		ExpectedFee idl.Nat `ic:"expected_fee" json:"expected_fee"`
	} `ic:"BadFee,variant" json:"BadFee,omitempty"`
	CreatedInFuture *struct {
		LedgerTime uint64 `ic:"ledger_time" json:"ledger_time"`
	} `ic:"CreatedInFuture,variant" json:"CreatedInFuture,omitempty"`
	TooOld            *idl.Null `ic:"TooOld,variant" json:"TooOld,omitempty"`
	InsufficientFunds *struct {
		Balance idl.Nat `ic:"balance" json:"balance"`
	} `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
}

type TransferFromArgs struct {
	To                Account  `ic:"to" json:"to"`
	Fee               *idl.Nat `ic:"fee,omitempty" json:"fee,omitempty"`
	SpenderSubaccount *[]byte  `ic:"spender_subaccount,omitempty" json:"spender_subaccount,omitempty"`
	From              Account  `ic:"from" json:"from"`
	Memo              *[]byte  `ic:"memo,omitempty" json:"memo,omitempty"`
	CreatedAtTime     *uint64  `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount            idl.Nat  `ic:"amount" json:"amount"`
}

type TransferFromError struct {
	GenericError *struct {
		Message   string  `ic:"message" json:"message"`
		ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
	} `ic:"GenericError,variant" json:"GenericError,omitempty"`
	TemporarilyUnavailable *idl.Null `ic:"TemporarilyUnavailable,variant" json:"TemporarilyUnavailable,omitempty"`
	InsufficientAllowance  *struct {
		Allowance idl.Nat `ic:"allowance" json:"allowance"`
	} `ic:"InsufficientAllowance,variant" json:"InsufficientAllowance,omitempty"`
	BadBurn *struct {
		MinBurnAmount idl.Nat `ic:"min_burn_amount" json:"min_burn_amount"`
	} `ic:"BadBurn,variant" json:"BadBurn,omitempty"`
	Duplicate *struct {
		DuplicateOf idl.Nat `ic:"duplicate_of" json:"duplicate_of"`
	} `ic:"Duplicate,variant" json:"Duplicate,omitempty"`
	BadFee *struct {
		ExpectedFee idl.Nat `ic:"expected_fee" json:"expected_fee"`
	} `ic:"BadFee,variant" json:"BadFee,omitempty"`
	CreatedInFuture *struct {
		LedgerTime uint64 `ic:"ledger_time" json:"ledger_time"`
	} `ic:"CreatedInFuture,variant" json:"CreatedInFuture,omitempty"`
	TooOld            *idl.Null `ic:"TooOld,variant" json:"TooOld,omitempty"`
	InsufficientFunds *struct {
		Balance idl.Nat `ic:"balance" json:"balance"`
	} `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
}

type UpgradeArgs struct {
	ChangeArchiveOptions *ChangeArchiveOptions `ic:"change_archive_options,omitempty" json:"change_archive_options,omitempty"`
	TokenSymbol          *string               `ic:"token_symbol,omitempty" json:"token_symbol,omitempty"`
	TransferFee          *idl.Nat              `ic:"transfer_fee,omitempty" json:"transfer_fee,omitempty"`
	Metadata             *[]struct {
		Field0 string        `ic:"0,tuple" json:"0,tuple"`
		Field1 MetadataValue `ic:"1,tuple" json:"1,tuple"`
	} `ic:"metadata,omitempty" json:"metadata,omitempty"`
	ChangeFeeCollector *ChangeFeeCollector  `ic:"change_fee_collector,omitempty" json:"change_fee_collector,omitempty"`
	MaxMemoLength      *uint16              `ic:"max_memo_length,omitempty" json:"max_memo_length,omitempty"`
	IndexPrincipal     *principal.Principal `ic:"index_principal,omitempty" json:"index_principal,omitempty"`
	TokenName          *string              `ic:"token_name,omitempty" json:"token_name,omitempty"`
	FeatureFlags       *FeatureFlags        `ic:"feature_flags,omitempty" json:"feature_flags,omitempty"`
}

type Value struct {
	Int *idl.Int `ic:"Int,variant" json:"Int,omitempty"`
	Map *[]struct {
		Field0 string `ic:"0,tuple" json:"0,tuple"`
		Field1 Value  `ic:"1,tuple" json:"1,tuple"`
	} `ic:"Map,variant" json:"Map,omitempty"`
	Nat   *idl.Nat `ic:"Nat,variant" json:"Nat,omitempty"`
	Nat64 *uint64  `ic:"Nat64,variant" json:"Nat64,omitempty"`
	Blob  *[]byte  `ic:"Blob,variant" json:"Blob,omitempty"`
	Text  *string  `ic:"Text,variant" json:"Text,omitempty"`
	Array *Vec     `ic:"Array,variant" json:"Array,omitempty"`
}

type Value1 struct {
	Text *struct {
		Content string `ic:"content" json:"content"`
	} `ic:"Text,variant" json:"Text,omitempty"`
	TokenAmount *struct {
		Decimals uint8  `ic:"decimals" json:"decimals"`
		Amount   uint64 `ic:"amount" json:"amount"`
		Symbol   string `ic:"symbol" json:"symbol"`
	} `ic:"TokenAmount,variant" json:"TokenAmount,omitempty"`
	TimestampSeconds *struct {
		Amount uint64 `ic:"amount" json:"amount"`
	} `ic:"TimestampSeconds,variant" json:"TimestampSeconds,omitempty"`
	DurationSeconds *struct {
		Amount uint64 `ic:"amount" json:"amount"`
	} `ic:"DurationSeconds,variant" json:"DurationSeconds,omitempty"`
}

type Vec = []struct {
	Int *idl.Int `ic:"Int,variant" json:"Int,omitempty"`
	Map *[]struct {
		Field0 string `ic:"0,tuple" json:"0,tuple"`
		Field1 Value  `ic:"1,tuple" json:"1,tuple"`
	} `ic:"Map,variant" json:"Map,omitempty"`
	Nat   *idl.Nat `ic:"Nat,variant" json:"Nat,omitempty"`
	Nat64 *uint64  `ic:"Nat64,variant" json:"Nat64,omitempty"`
	Blob  *[]byte  `ic:"Blob,variant" json:"Blob,omitempty"`
	Text  *string  `ic:"Text,variant" json:"Text,omitempty"`
	Array *any     `ic:"Array,variant" json:"Array,omitempty"`
}

type API interface {
	Icrc2Approve(arg0 ApproveArgs) (*Result4, error)
}

// api is a client for the "icrc2" canister.
type api struct {
	*agent.Agent
	CanisterId principal.Principal
}

// NewAPI creates a new agent for the "icrc2" canister.
func NewAPI(canisterId icp.Principal, a *icp.Agent) (*api, error) {
	return &api{
		Agent:      a.Raw(),
		CanisterId: canisterId.Raw(),
	}, nil
}

// Archives calls the "archives" method on the "icrc2" canister.
func (a api) Archives() (*[]ArchiveInfo, error) {
	var r0 []ArchiveInfo
	if err := a.Agent.Query(
		a.CanisterId,
		"archives",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetBlocks calls the "get_blocks" method on the "icrc2" canister.
func (a api) GetBlocks(arg0 GetBlocksRequest) (*GetBlocksResponse, error) {
	var r0 GetBlocksResponse
	if err := a.Agent.Query(
		a.CanisterId,
		"get_blocks",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetDataCertificate calls the "get_data_certificate" method on the "icrc2" canister.
func (a api) GetDataCertificate() (*DataCertificate, error) {
	var r0 DataCertificate
	if err := a.Agent.Query(
		a.CanisterId,
		"get_data_certificate",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// GetTransactions calls the "get_transactions" method on the "icrc2" canister.
func (a api) GetTransactions(arg0 GetBlocksRequest) (*GetTransactionsResponse, error) {
	var r0 GetTransactionsResponse
	if err := a.Agent.Query(
		a.CanisterId,
		"get_transactions",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc103GetAllowances calls the "icrc103_get_allowances" method on the "icrc2" canister.
func (a api) Icrc103GetAllowances(arg0 GetAllowancesArgs) (*Result, error) {
	var r0 Result
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc103_get_allowances",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc106GetIndexPrincipal calls the "icrc106_get_index_principal" method on the "icrc2" canister.
func (a api) Icrc106GetIndexPrincipal() (*Result1, error) {
	var r0 Result1
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc106_get_index_principal",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc10SupportedStandards calls the "icrc10_supported_standards" method on the "icrc2" canister.
func (a api) Icrc10SupportedStandards() (*[]StandardRecord, error) {
	var r0 []StandardRecord
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc10_supported_standards",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1BalanceOf calls the "icrc1_balance_of" method on the "icrc2" canister.
func (a api) Icrc1BalanceOf(arg0 Account) (*idl.Nat, error) {
	var r0 idl.Nat
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_balance_of",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Decimals calls the "icrc1_decimals" method on the "icrc2" canister.
func (a api) Icrc1Decimals() (*uint8, error) {
	var r0 uint8
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_decimals",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Fee calls the "icrc1_fee" method on the "icrc2" canister.
func (a api) Icrc1Fee() (*idl.Nat, error) {
	var r0 idl.Nat
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_fee",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Metadata calls the "icrc1_metadata" method on the "icrc2" canister.
func (a api) Icrc1Metadata() (*[]struct {
	Field0 string        `ic:"0,tuple" json:"0,tuple"`
	Field1 MetadataValue `ic:"1,tuple" json:"1,tuple"`
}, error) {
	var r0 []struct {
		Field0 string        `ic:"0,tuple" json:"0,tuple"`
		Field1 MetadataValue `ic:"1,tuple" json:"1,tuple"`
	}
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_metadata",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1MintingAccount calls the "icrc1_minting_account" method on the "icrc2" canister.
func (a api) Icrc1MintingAccount() (**Account, error) {
	var r0 *Account
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_minting_account",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Name calls the "icrc1_name" method on the "icrc2" canister.
func (a api) Icrc1Name() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_name",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1SupportedStandards calls the "icrc1_supported_standards" method on the "icrc2" canister.
func (a api) Icrc1SupportedStandards() (*[]StandardRecord, error) {
	var r0 []StandardRecord
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_supported_standards",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Symbol calls the "icrc1_symbol" method on the "icrc2" canister.
func (a api) Icrc1Symbol() (*string, error) {
	var r0 string
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_symbol",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1TotalSupply calls the "icrc1_total_supply" method on the "icrc2" canister.
func (a api) Icrc1TotalSupply() (*idl.Nat, error) {
	var r0 idl.Nat
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc1_total_supply",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc1Transfer calls the "icrc1_transfer" method on the "icrc2" canister.
func (a api) Icrc1Transfer(arg0 TransferArg) (*Result2, error) {
	var r0 Result2
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc1_transfer",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc21CanisterCallConsentMessage calls the "icrc21_canister_call_consent_message" method on the "icrc2" canister.
func (a api) Icrc21CanisterCallConsentMessage(arg0 ConsentMessageRequest) (*Result3, error) {
	var r0 Result3
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc21_canister_call_consent_message",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc2Allowance calls the "icrc2_allowance" method on the "icrc2" canister.
func (a api) Icrc2Allowance(arg0 AllowanceArgs) (*Allowance1, error) {
	var r0 Allowance1
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc2_allowance",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc2Approve calls the "icrc2_approve" method on the "icrc2" canister.
func (a api) Icrc2Approve(arg0 ApproveArgs) (*Result4, error) {
	var r0 Result4
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc2_approve",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc2TransferFrom calls the "icrc2_transfer_from" method on the "icrc2" canister.
func (a api) Icrc2TransferFrom(arg0 TransferFromArgs) (*Result5, error) {
	var r0 Result5
	if err := a.Agent.Call(
		a.CanisterId,
		"icrc2_transfer_from",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetArchives calls the "icrc3_get_archives" method on the "icrc2" canister.
func (a api) Icrc3GetArchives(arg0 GetArchivesArgs) (*[]ICRC3ArchiveInfo, error) {
	var r0 []ICRC3ArchiveInfo
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc3_get_archives",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetBlocks calls the "icrc3_get_blocks" method on the "icrc2" canister.
func (a api) Icrc3GetBlocks(arg0 []GetBlocksRequest) (*GetBlocksResult, error) {
	var r0 GetBlocksResult
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc3_get_blocks",
		[]any{arg0},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3GetTipCertificate calls the "icrc3_get_tip_certificate" method on the "icrc2" canister.
func (a api) Icrc3GetTipCertificate() (**ICRC3DataCertificate, error) {
	var r0 *ICRC3DataCertificate
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc3_get_tip_certificate",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// Icrc3SupportedBlockTypes calls the "icrc3_supported_block_types" method on the "icrc2" canister.
func (a api) Icrc3SupportedBlockTypes() (*[]SupportedBlockType, error) {
	var r0 []SupportedBlockType
	if err := a.Agent.Query(
		a.CanisterId,
		"icrc3_supported_block_types",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}

// IsLedgerReady calls the "is_ledger_ready" method on the "icrc2" canister.
func (a api) IsLedgerReady() (*bool, error) {
	var r0 bool
	if err := a.Agent.Query(
		a.CanisterId,
		"is_ledger_ready",
		[]any{},
		[]any{&r0},
	); err != nil {
		return nil, err
	}
	return &r0, nil
}
